## Meta Ads

#### Useful links:
- [Get a Developer account](https://developers.facebook.com/async/registration/dialog/?src=default)
- [Identity and Location Confirmation](Facebook.com/ID)
- [Meta Ads API Documentation](https://www.facebook.com/ads/library/api/)
- [Meta Ads API - Ads Archive Reference](https://developers.facebook.com/docs/graph-api/reference/ads_archive/)

In [1]:
# requirements
%pip install pandas==2.3.2 requests==2.32.5 python-dotenv==1.1.1 pandera==0.26.1

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas==2.3.2 in c:\users\rapha\appdata\roaming\python\python311\site-packages (2.3.2)
Requirement already satisfied: requests==2.32.5 in c:\users\rapha\appdata\roaming\python\python311\site-packages (2.32.5)
Requirement already satisfied: python-dotenv==1.1.1 in c:\users\rapha\appdata\roaming\python\python311\site-packages (1.1.1)
Requirement already satisfied: pandera==0.26.1 in c:\users\rapha\appdata\roaming\python\python311\site-packages (0.26.1)
Requirement already satisfied: numpy>=1.23.2 in c:\programdata\anaconda3\lib\site-packages (from pandas==2.3.2) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas==2.3.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas==2.3.2) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas==2.3.2) (2023.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests==2.32.5) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests==2.32.5) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests==2.32.5) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests==2.32.5) (2025.4.26)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from pandera==0.26.1) (23.1)
Requirement already satisfied: pydantic in c:\users\rapha\appdata\roaming\python\python311\site-packages (from pandera==0.26.1) (2.8.2)
Requirement already satisfied: typeguard in c:\users\rapha\appdata\roaming\python\python311\site-packages (from pandera==0.26.1) (4.4.4)
Requirement already satisfied: typing_extensions in c:\users\rapha\appdata\roaming\python\python311\site-packages (from pandera==0.26.1) (4.15.0)
Requirement already satisfied: typing_inspect>=0.6.0 in c:\users\rapha\appdata\roaming\python\python311\site-packages (from pandera==0.26.1) (0.9.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.3.2) (1.16.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\programdata\anaconda3\lib\site-packages (from typing_inspect>=0.6.0->pandera==0.26.1) (1.0.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic->pandera==0.26.1) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\rapha\appdata\roaming\python\python311\site-packages (from pydantic->pandera==0.26.1) (2.20.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import os
import json
import glob
import pandas as pd
import pandera.pandas as pa
from pandera.errors import SchemaErrors
import requests
from dotenv import load_dotenv
from datetime import datetime
from time import sleep

In [2]:
import sys

print("Python version:")
print(sys.version)

Python version:
3.11.10 | packaged by Anaconda, Inc. | (main, Oct  3 2024, 07:22:26) [MSC v.1929 64 bit (AMD64)]

In [3]:
# environment variables
load_dotenv()
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN") # Token expires in
FILEPATH = os.getenv("FILEPATH")

#### Meta Ads API Available Parameters

- ad_active_status: *enum {ACTIVE, ALL, INACTIVE}* <span style="color:red">**(DEFAULT: Active)**</span>
- ad_delivery_date_max: *str*
- ad_delivery_date_min: *str*
- ad_reached_countries: *array<enum> (countries abbreviations)*
- ad_type: *enum {ALL, EMPLOYMENT_ADS, FINANCIAL_PRODUCTS_AND_SERVICES_ADS, HOUSING_ADS, POLITICAL_AND_ISSUE_ADS}* <span style="color:red">**(DEFAULT: ALL)**</span>
- bylines: *array<str>*
- delivery_by_region: *array<str>*
- estimated_audience_size_max: *int64*
- estimated_audience_size_min: *int64*
- languages: *array<str>*
- media_type: *enum {ALL, IMAGE, MEME, VIDEO, NONE}*
- publisher_platforms: *array<enum {FACEBOOK, INSTAGRAM, AUDIENCE_NETWORK, MESSENGER, WHATSAPP, OCULUS, THREADS}>*
- search_page_ids: *array<int64>*
- search_terms: *str* <span style="color:red">**(DEFAULT: "")**</span>
- search_type: *enum {KEYWORD_UNORDERED, KEYWORD_EXACT_PHRASE}* <span style="color:red">**(DEFAULT: KEYWORD_UNORDERED)**</span>
- unmask_removed_content: *bool* <span style="color:red">**(DEFAULT: False)**</span>

In [4]:
# Expected Payload
# It consists of a dict containing the access token and the desired parameters for the request
# Must have search_terms or search_page_ids parameters
# Please update the variable below with the desired search parameters
payload = {
            "access_token": ACCESS_TOKEN,
        }

#### Meta Ads API Available Fields

- All countries:
    * id
    * ad_creation_time
    * ad_creative_bodies
    * ad_creative_link_captions
    * ad_creative_link_descriptions
    * ad_creative_link_titles
    * ad_delivery_start_time
    * ad_delivery_stop_time
    * ad_snapshot_url
    * bylines
    * currency
    * delivery_by_region
    * demographic_distribution
    * estimated_audience_size
    * impressions
    * languages
    * page_id
    * page_name
    * publisher_platforms
    * spend
 
- Brazil only:
    * age_country_gender_reach_breakdown
    * br_total_reach
    * target_ages
    * target_gender
    * target_locations
    * total_reach_by_location
    
- EU only:
    * age_country_gender_reach_breakdown
    * beneficiary_payers
    * eu_total_reach
    * target_ages
    * target_gender
    * target_locations
    * total_reach_by_location

#### API Connection

In [5]:
# fields should be a string of selected fields separeted by comma, without any blank space
# e.g: "id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions"
fields = ""

In [6]:
# newest api version is v23.0 (08-09-2025)
api_url = f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"

In [7]:
# API Requests
def request_to_api(session, payload, api_url):
    response = session.get(api_url, params=payload)
    return response.json()

# Pagination
def paginate(session, payload, response):
    collected_ads = []
    while "paging" in response:
        next_page_url = response["paging"].get("next", "")
        sleep(1)
        response = request_to_api(session,payload, next_page_url)
        # The implementation of pagination ends here
        # Feel free to change implementation to extract data
        data = response.get("data", [])
        collected_ads.extend(data)
    return collected_ads

# Session
session = requests.Session()

### Special Criteria

**SC1: Does the platform provide an API to access its ad repository and extract data on advertising content?**

*This item verifies whether the platform provides an ad repository API with at least one endpoint for programmatically extracting advertising data. Full availability is confirmed when the API returns information on ads across all categories. The assessment should confirm that the endpoint allows the retrieval and storage of ad data without requiring privileged or internal access beyond standard developer registration.*

In [9]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET SEARCH TERM
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"], 
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": False
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data in response")
    print(response)

Got 25 ads in a single request

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,languages,page_id,page_name,publisher_platforms,target_ages,target_gender,target_locations,total_reach_by_location,ad_creative_link_descriptions
0,4192086697717648,2025-05-05,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-05,2025-05-05,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],434190399773378,Enseignement-Apprentissage,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 36}]",NaN
1,566436209821750,2025-05-05,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-05,2025-05-06,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],355127741015217,Real Team,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 11}]",NaN
2,543784622115975,2025-05-03,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-04,2025-05-04,"[{'country': 'FI', 'age_gender_breakdowns': [{...",[en],100855685416689,Ale Memes esse é o foi,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2}]",NaN
3,569384776193327,2025-05-03,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-03,2025-05-06,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],109194464742841,UsbonGarrh,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Austria', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 181}]",NaN
4,1780320716164479,2025-05-02,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-02,2025-05-03,"[{'country': 'FI', 'age_gender_breakdowns': [{...",[en],105870398554650,Michael EM,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6}]",NaN
5,708779748236211,2025-04-30,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-30,2025-05-01,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],105774929142171,Malucus,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 9}]",NaN
6,1225703642407613,2025-04-30,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-30,2025-05-03,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],102242762540264,Deus é fiel,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 75}]",NaN
7,990332916558558,2025-04-27,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-27,2025-04-29,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],104310028613716,Hustle Nation Team Tubombeko,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 1}]",NaN
8,1256665679256719,2025-07-31,[Login to get free summons😍\nGift Code: vip888🎁],[itunes.apple.com],[🎮 Join now and get 1000 summons FREE!],2025-08-01,2025-08-03,"[{'country': 'DE', 'age_gender_breakdowns': [{...",NaN,126004137251949,Courage Evolution·ⅷ,"[facebook, instagram, audience_network, messen...","[21, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 8}, {'key': 'GB', 'val...",NaN
9,2029047231250712,2025-11-16,[You’re not crazy. You’re just not getting the...,[nas.io],"[Stop guessing. Start Healing, naturally!, Sto...",2025-11-16,2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],1476126802688462,So You Think You Are Healthy,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 65}]","[Comment QUIZ to get the free link now!, Comme..."
10,468492669268944,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-24,2024-12-28,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 192}]",NaN
11,540462482317039,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-26,2024-12-28,"[{'country': 'SE', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 4}]",NaN
12,927457872686945,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-23,2024-12-24,"[{'country': 'ES', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 10002}]",NaN
13,1118856549901694,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-25,2024-12-28,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 13}]",NaN
14,1149767699841006,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-23,2025-01-04,"[{'country': 'EE', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2229}]",NaN
15,1198154008406828,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-19,2024-12-21,"[{'country': 'EE', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 5213}]",NaN
16,1645469656179516,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-25,2024-12-27,"[{'country': 'IT', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 26032}]",NaN
17,1681368622408808,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-26,2024-12-28,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 8067}]",NaN
18,1699924333908780,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-19,2025-01-01,"[{'country': 'RO', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 74}]",NaN
19,1990654091358510,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-24,2024-12-25,"[{'country': 'CY', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6337}]",NaN
20,659209690345526,2025-10-21,[Discover how to take control of your blood su...,[nas.io],"[Join Our FREE Webinar!, Join Our FREE Webinar...",2025-10-21,2025-10-22,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],694879470385928,No Fuss Health,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 127}]","[Secure your spot today, Secure your spot toda..."
21,1510983603181878,2025-10-21,[Always tired or sleepy after eating? That’s y...,[nas.io],"[Join Our Free Webinar Now!, Join Our Free Web...",2025-10-22,2025-10-28,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],694879470385928,No Fuss Health,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 122}]","[Save your seat — Limited slots remaining, Sav..."
22,573867262268518,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],[Chronic Overthinking Test 👉],2024-12-23,2025-02-22,"[{'country': 'MQ', 'age_gender_breakdowns': [{...",[en],214946655027813,Your Personal Coach Sophia,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 18506}]",NaN
23,1238312724100050,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],"[Chronic Overthinking Test 👉, Chronic Overthin...",2024-12-23,2024-12-27,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],214946655027813,Your Personal Coach Sophia,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 1935}]",NaN
24,1266941774632571,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],[Chronic Overthinking Test 👉],2024-12-23,2024-12-26,"[{'country': 'NL', 'age_gender_breakdowns': [{...",[en],213571821842759,Mindway,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 3002}]",NaN

In [10]:
# Checking type of ad in response
political_fields = ["bylines", "currency", "delivery_by_region", "demographic_distribution", "estimated_audience_size", "impressions", "spend"]
political_ads = 0
other_ads = 0
for ad in response["data"]:
    has_political_fields = False
    for k in ad.keys():
        if k in political_fields:
            has_political_fields = True
            break
    if has_political_fields:
        political_ads += 1
    else:
        other_ads += 1

print("Total political ads:", political_ads)
print("Total other categories ads:", other_ads)

Total political ads: 0
Total other categories ads: 25

In [11]:
# EMPLOYMENT_ADS
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,page_id,page_name,publisher_platforms"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET SEARCH TERM
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "EMPLOYMENT_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in EMPLOYMENT_ADS in a single request")
    print(response)
else:
    print("No data found in EMPLOYMENT_ADS")
    print(response)

Got 25 in EMPLOYMENT_ADS in a single request

In [12]:
# FINANCIAL_PRODUCTS_AND_SERVICES_ADS
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,page_id,page_name,publisher_platforms"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET SEARCH TERM
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "FINANCIAL_PRODUCTS_AND_SERVICES_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in FINANCIAL_PRODUCTS_AND_SERVICES_ADS in a single request")
    print(response)
else:
    print("No data found in FINANCIAL_PRODUCTS_AND_SERVICES_ADS")
    print(response)

Got 25 in FINANCIAL_PRODUCTS_AND_SERVICES_ADS in a single request

In [13]:
# HOUSING_ADS
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,page_id,page_name,publisher_platforms"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET SEARCH TERM
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "HOUSING_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in HOUSING_ADS in a single request")
    print(response)
else:
    print("No data found in HOUSING_ADS")
    print(response)

Got 25 in HOUSING_ADS in a single request

In [14]:
# POLITICAL_AND_ISSUE_ADS
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET SEARCH TERM
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in POLITICAL_AND_ISSUE_ADS in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found in POLITICAL_AND_ISSUE_ADS")
    print(response)

Got 25 ads in POLITICAL_AND_ISSUE_ADS in a single request

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_titles,ad_delivery_start_time,age_country_gender_reach_breakdown,bylines,currency,estimated_audience_size,...,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location,delivery_by_region,demographic_distribution,ad_delivery_stop_time,ad_creative_link_descriptions
0,820201220997208,2025-11-17,"[Every day, Sophie feels the pressure – at hom...",[railwaychildren.org.uk],"[This Christmas, children like Sophie can’t wa...",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Railway Children,GBP,"{'lower_bound': '100001', 'upper_bound': '5000...",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 23}]",NaN,NaN,NaN,NaN
1,2304576016640979,2025-11-17,[Health is a major issue on doorsteps in Galas...,[survey.labour.org.uk],[Your views matter],2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...","Midlothian South, Tweeddale and Lauderdale Con...",GBP,"{'lower_bound': '10001', 'upper_bound': '50000'}",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'Galashiels, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 310}]","[{'percentage': '1', 'region': 'Scotland'}]","[{'percentage': '0.032362', 'age': '18-24', 'g...",NaN,NaN
2,1471437670627318,2025-11-17,[Health is a major issue on doorsteps in Galas...,[survey.labour.org.uk],[Your views matter],2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...","Midlothian South, Tweeddale and Lauderdale Con...",GBP,"{'lower_bound': '10001', 'upper_bound': '50000'}",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'Peebles, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 131}]","[{'percentage': '1', 'region': 'Scotland'}]","[{'percentage': '0.022901', 'age': '18-24', 'g...",2025-11-17,NaN
3,2355445218205574,2025-11-17,[✈️🇪🇸 Travelling to Spain in 2025? Read this b...,[healthplanspain.com],[Schengen Entry Checks in Spain 2025 - Guide f...,2025-11-17,"[{'country': 'IE', 'age_gender_breakdowns': [{...",NaN,EUR,NaN,...,"[facebook, instagram, audience_network, messen...","{'lower_bound': '0', 'upper_bound': '99'}","[20, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 88}, {'key': 'GB', 'va...","[{'percentage': '6.3E-5', 'region': ''Asir Reg...","[{'percentage': '0.035656', 'age': '18-24', 'g...",2025-11-18,[Stricter border controls are now in force in ...
4,1583691626406370,2025-11-17,NaN,"[instagram.com, instagram.com, instagram.com, ...",[Médecins Sans Frontières / Doctors Without Bo...,2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Médecins Sans Frontières / Doctors Without Bor...,GBP,{'lower_bound': '1000001'},...,[instagram],"{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 1211}]","[{'percentage': '0.837883', 'region': 'England...","[{'percentage': '0.257903', 'age': '18-24', 'g...",NaN,NaN
5,1158136649632381,2025-11-17,[Action For Humanity is on the ground in Yemen...,[actionforhumanity.org],"[Voices From Yemen, Voices From Yemen]",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Action For Humanity,GBP,"{'lower_bound': '100001', 'upper_bound': '5000...",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[20, 55]",All,"[{'name': 'West Bromwich, United Kingdom', 'nu...","[{'key': 'GB', 'value': 35}]",NaN,NaN,NaN,"[Action For Humanity, Action For Humanity]"
6,766996016361133,2025-11-17,[Action For Humanity is on the ground in Yemen...,[actionforhumanity.org],"[Voices From Yemen, Voices From Yemen]",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Action For Humanity,GBP,"{'lower_bound': '10001', 'upper_bound': '50000'}",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[20, 55]",All,"[{'name': 'West Bromwich, United Kingdom', 'nu...","[{'key': 'GB', 'value': 22}]",NaN,NaN,NaN,"[Action For Humanity, Action For Humanity]"
7,1506911813892989,2025-11-17,[Action For Humanity is on the ground in Yemen...,[actionforhumanity.org],"[Voices From Yemen, Voices From Yemen]",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Action For Humanity,GBP,{'lower_bound': '1000001'},...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[20, 55]",All,"[{'name': 'West Bromwich, United Kingdom', 'nu...","[{'key': 'GB', 'value': 18}]",NaN,NaN,NaN,"[Action For Humanity, Action For Humanity]"
8,4072423809674987,2025-11-17,"[When crisis strikes, families can lose access...",[who.foundation],[WHO On the Frontlines Worldwide],2025-11-17,"[{'country': 'ES', 'age_gender_breakdowns': [{...",NaN,CHF,NaN,...,"[facebook, instagram, messenger, threads]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'Netherlands', 'num_obfuscated': 0, ...","[{'key': 'EU', 'value': 34}, {'key': 'GB', 'va...","[{'percentage': '0.046448', 'region': 'Abu Dha...","[{'percentage': '0.019126', 'age': '18-24', 'g...",2025-11-18,[WHO teams act fast in crises across the globe...
9,1201738788490856,2025-11-17,[35 years in the union movement.\n\n🏢 From loc...,NaN,NaN,2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Re-Elect Christina McAnea for General Secretary,GBP,"{'lower_bound': '500001', 'upper_bound': '1000...",...,[facebook],"{'lower_bound': '100', 'upper_bound': '199'}","[18, 65]",Women,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 17692}]","[{'percentage': '0.834905', 'region': 'England...","[{'percentage': '0.004373', 'age': '18-24', 'g...",NaN,NaN
10,1018345883784718,2025-11-17,[We’re delighted to have the support of Kent W...,[change.org],[We Can Make an Impact.],2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,GBP,NaN,...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[25, 65]",All,"[{'name': 'Margate, Kent, United Kingdom', 'nu...","[{'key': 'GB', 'value': 164}]","[{'percentage': '1', 'region': 'England'}]","[{'percentage': '0.042683', 'age': '25-34', 'g...",2025-11-18,[Stop Dog Fouling in Thanet – Make TDC Enforce...
11,25547504004847190,2025-11-16,[A £1billion underspend from the SNP means our...,NaN,NaN,2025-11-16,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,GBP,"{'lower_bound': '50001', 'upper_bound': '100000'}",...,[facebook],"{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'AB10 1, United Kingdom', 'num_obfus...","[{'key': 'GB', 'value': 85}]",NaN,NaN,2025-11-17,NaN
12,865891392528045,2025-11-16,"[“When we invest in people, we save lives — an...",NaN,NaN,2025-11-16,"[{'country': 'NL', 'age_gender_breakdowns': [{...",NaN,UAH,NaN,...,"[facebook, instagram, audience_network, threads]","{'lower_bound': '100', 'upper_bound': '199'}","[18, 65]",All,"[{'name': 'Italy', 'num_obfuscated': 0, 'type'...","[{'key': 'EU', 'value': 2690}, {'key': 'GB', '...","[{'percentage': '0.049972', 'region': 'Abkhazi...","[{'percentage': '0.101685', 'age': '18-24', 'g...",2025-11-18,NaN
13,869895502220383,2025-11-16,[“Global Fund saved my life at least four time...,NaN,NaN,2025-11-16,"[{'country': 'CZ', 'age_gender_breakdowns': [{...",NaN,UAH,{'lower_bound': '1000001'},...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'Italy', 'num_obfuscated': 0, 'type'...","[{'key': 'EU', 'value': 8}, {'key': 'GB', 'val...",NaN,NaN,2025-11-16,NaN
14,2702739236731672,2025-11-16,[📣 Volunteers Needed – Help Us Deliver Flyers!...,[change.org],[Can you spare a minute to help this campaign?],2025-11-16,"[{'country': 'GB', 'age_gender_breakdowns': [{...",GRASS Cliftonville CIC,GBP,"{'lower_bound': '100001', 'upper_bound': '5000...",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'Ramsgate, United Kingdom', 'num_obf...","[{'key': 'GB', 'value': 1593}]","[{'percentage': '1', 'region': 'England'}]","[{'percentage': '0.002451', 'age': '18-24', 'g...",2025-11-18,[Stop Dog Fouling in Thanet – Make TDC Enforce...
15,4075866789347012,2025-11-15,[Talking Points this Sunday at 9am],[instagram.com],NaN,2025-11-15,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,GBP,"{'lower_bound': '50001', 'upper_bound': '100000'}",...,[instagram],"{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'LE4 0, United Kingdom', 'num_obfusc...","[{'key': 'GB', 'value': 373}]","[{'percentage': '1', 'region': 'England'}]","[{'percentage': '0.02122', 'age': '18-24', 'ge...",2025-11-16,NaN
16,1491394831915817,2025-11-15,[Our thoughts are with all those affected by s...,[nebriefing.org],[National Emergency Briefing on climate & nature],2025-11-15,"[{'country': 'GB', 'age_gender_breakdowns': [{...",National Emergency Briefing,GBP,{'lower_bound': '1000001'},...,"[facebook, instagram]","{'lower_bound': '200', 'upper_bound': '299'}","[18, 65]",All,"[{'name': 'Wales, United Kingdom', 'num_obfusc...","[{'key': 'GB', 'value': 36329}]","[{'percentage': '1', 'region': 'Wales'}]","[{'percentage': '0.026229', 'age': '18-24', 'g...",NaN,[An unfiltered assessment of the latest threat...
17,1368507788086212,2025-11-15,[The SNP’s plan is working - NHS waiting lists...,[facebook.com],[Zen Ghani SNP],2025-11-15,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Zen Ghani SNP,GBP,"{'lower_bound': '50001', 'upper_bound': '100000'}",...,[facebook],"{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'G43 1, United Kingdom', 'num_obfusc...","[{'key': 'GB', 'value': 1470}]","[{'percentage': '1', 'region': 'Scotland'}]","[{'percentage': '0.004664', 'age': '18-24', 'g...",NaN,NaN
18,853565240499142,2025-11-15,[We’re delighted to have the support of Kent W...,[change.org],[Sign the Petition Now],2025-11-15,"[{'country': 'GB', 'age_gender_breakdowns': [{...",GRASS Cliftonville CIC,GBP,"{'lower_bound': '100001', 'upper_bound': '5000...",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'Ramsgate, United Kingdom', 'num_obf...","[{'key': 'GB', 'value': 575}]","[{'percentage': '1', 'region': 'England'}]","[{'percentage': '0.008651', 'age': '18-24', 'g...",2025-11-16,[Stop Dog Fouling in Thanet – Make TDC Enforce...
19,766947929732943,2025-11-14,[🏃‍♀️ Choose your runner\n\nAll have the same ...,[givewheel.com],NaN,2025-11-14,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,GBP,"{'lower_bound': '500001', 'upper_bound': '1000...",...,[facebook],"{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'London, United Kingdom', 'num_obfus...","[{'key': 'GB', 'value': 3515}]","[{'percentage': '1', 'region': 'England'}]","[{'percentage': '0.001131', 'age': '18-24', 'g...",2025-11-16,NaN
20,846137747884428,2025-11-14,[35 years in the union movement.\n\n🏢 From loc...,NaN,NaN,2025-11-14,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Re-Elect Christina McAnea for General Secretary,GBP,"{'lower_bound': '500001', 'upper_bound': '1000...",...,[facebook],"{'lower_bound': '300', 'upper_bound': '399'}","[18, 65]",Women,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 30595}]","[{'percentage': '0.829814', 'region': 'England...","[{'percentage': '0.00353', 'age': '18-24', 'ge...",2025-11-17,NaN
21,1864870594445656,2025-11-14,[35 years in the union movement.\n\n🏢 From loc...,[votechristina.org.uk],NaN,2025-11-14,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Re-Elect Christina McAnea for General Secretary,GBP,"{'lower_bound': '500001', 'upper_bound': '1000...",...,[facebook],"{'lower_bound': '100', 'upper_bound': '199'}","[18, 65]",Women,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 10891}]","[{'percentage': '0.804342', 'region': 'England...","[{'percentage': '0.004948', 'age': '18-24', 'g...",NaN,NaN
22,4307252356177172,2025-11-14,[A two-year-old in Gaza is fighting to survive...,[muslimrelief.org.uk],"[Stand With Gaza’s Most Vulnerable, Stand With...",2025-11-14,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Muslim Relief,GBP,"{'lower_bound': '100001', 'upper_bound': '5000...",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[21, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 184}]","[{'percentage': '0.934783', 'region': 'England...","[{'percentage': '0.038043', 'age': '18-24', 'g...",NaN,NaN
23,2024356928405238,2025-11-14,[Our ambition is to make Wales the most Vetera...,NaN,NaN,2025-11-14,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Welsh Conservative Party,GBP,{'lower_bound': '1000001'},...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",All,"[{'name': 'Wales, United Kingdom', 'num_obfusc...","[{'key': 'GB', 'value': 6917}]","[{'percentage': '1', 'region': 'Wales'}]","[{'percentage': '0.001489', 'age': '18-24', 'g...",NaN,NaN
24,3762748727354087,2025-11-14,"[If you’re pregnant, you’re eligible for the f...",[nhs.uk],[Winter vaccinations and winter health],2025-11-14,"[{'country': 'GB', 'age_gender_breakdowns': [{...",Warrington Borough Council,GBP,"{'lower_bound': '100001', 'upper_bound': '5000...",...,"[facebook, instagram]","{'lower_bound': '0', 'upper_bound': '99'}","[18, 65]",Women,"[{'name': 'Warrington, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 1562}]","[{'percentage': '1', 'region': 'England'}]","[{'percentage': '0.048964', 'age': '18-24', 'g...",NaN,"[Find advice on how to stay well in winter, in..."

**SC3: Can data from both active and inactive ads be extracted?**

*This item verifies whether the platform allows the extraction of ad data through either the GUI or the API, from at least one day after publication to at least one year prior. Full availability is confirmed when both active and inactive ad data are delivered across all ad categories. The assessment should test the interface and endpoints to confirm whether both active and inactive ads can be retrieved.*

In [15]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET SEARCH TERM
active_payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ACTIVE",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
inactive_payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "INACTIVE",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
active_response = request_to_api(session, active_payload, api_url)
inactive_response = request_to_api(session, inactive_payload, api_url)
if "data" in active_response:
    print(f"Got {len(active_response['data'])} ACTIVE ads in a single request")
    active_df = pd.DataFrame(active_response["data"])
    display(active_df)
else:
    print("No ACTIVE ads were found")
    print(active_response)
if "data" in inactive_response:
    print(f"Got {len(inactive_response['data'])} INACTIVE ads in a single request")
    inactive_df = pd.DataFrame(inactive_response["data"])
    display(inactive_df)
else:
    print("No INACTIVE ads were found")
    print(inactive_response)

Got 25 ACTIVE ads in a single request

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,age_country_gender_reach_breakdown,languages,page_id,page_name,publisher_platforms,target_ages,target_gender,target_locations,total_reach_by_location
0,667790906185052,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 557}]"
1,668782399418691,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 59}]"
2,794155346789288,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 1019}]"
3,1112181087746067,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 104}]"
4,1163290458618803,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 13}]"
5,1169616888415859,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 204}]"
6,1293431029137185,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 19}]"
7,1323355529118704,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 29}]"
8,1347976580373015,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 10}]"
9,1534141287700880,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 16}]"
10,1578940306852649,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 30}]"
11,1645755500130868,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 283}]"
12,1655015275459112,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 5}]"
13,1761672311177541,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 70}]"
14,1782337612487808,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 218}]"
15,1788184081827726,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 636}]"
16,1825201634768633,2025-10-31,"[Starting at Woking Leisure Centre, you’ll run...",[fb.me],[The Surrey Half Marathon will take place on t...,"[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 1}]"
17,1882016239080138,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 95}]"
18,1968649370370049,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 88}]"
19,2100271747405998,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 110}]"
20,2237351653419948,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 78}]"
21,2610973709239822,2025-10-30,[The Coventry Half Marathon returns on the 19t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Birmingham, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 10}]"
22,25443033681969536,2025-10-31,[The Surrey Half Marathon will take place on t...,[fb.me],"[Run for mental health research, Run for menta...","[Raise Money For Mental Health Research, Raise...",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],678851558858294,MQ Mental Health Research,"[facebook, instagram, audience_network]","[19, 51]",All,"[{'name': 'Crawley, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 191}]"
23,730803949308737,2025-11-10,"[I was working out, walking 10k steps, skippin...",[health-time.com],[Read An Endocrinologist Reveals: Blood Sugar ...,[Insulin Resistance Detox for Beginners],2025-11-11,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],764071750116449,Healthtime,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 1872}]"
24,853488807118330,2025-11-10,[Anti-Inflammatory Diet For Women in Menopause...,[healthinsider.news],[Research shows that around 66% of menopausal ...,[Inflammation Detox for Women in Menopause],2025-11-11,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],1835332883255867,Health Insider,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 437}]"

Got 25 INACTIVE ads in a single request

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,languages,page_id,page_name,publisher_platforms,target_ages,target_gender,target_locations,total_reach_by_location,ad_creative_link_descriptions
0,4192086697717648,2025-05-05,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-05,2025-05-05,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],434190399773378,Enseignement-Apprentissage,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 36}]",NaN
1,566436209821750,2025-05-05,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-05,2025-05-06,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],355127741015217,Real Team,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 11}]",NaN
2,543784622115975,2025-05-03,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-04,2025-05-04,"[{'country': 'FI', 'age_gender_breakdowns': [{...",[en],100855685416689,Ale Memes esse é o foi,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2}]",NaN
3,569384776193327,2025-05-03,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-03,2025-05-06,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],109194464742841,UsbonGarrh,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Austria', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 181}]",NaN
4,1780320716164479,2025-05-02,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-02,2025-05-03,"[{'country': 'FI', 'age_gender_breakdowns': [{...",[en],105870398554650,Michael EM,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6}]",NaN
5,708779748236211,2025-04-30,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-30,2025-05-01,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],105774929142171,Malucus,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 9}]",NaN
6,1225703642407613,2025-04-30,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-30,2025-05-03,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],102242762540264,Deus é fiel,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 75}]",NaN
7,990332916558558,2025-04-27,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-27,2025-04-29,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],104310028613716,Hustle Nation Team Tubombeko,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 1}]",NaN
8,1256665679256719,2025-07-31,[Login to get free summons😍\nGift Code: vip888🎁],[itunes.apple.com],[🎮 Join now and get 1000 summons FREE!],2025-08-01,2025-08-03,"[{'country': 'DE', 'age_gender_breakdowns': [{...",NaN,126004137251949,Courage Evolution·ⅷ,"[facebook, instagram, audience_network, messen...","[21, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 8}, {'key': 'GB', 'val...",NaN
9,2029047231250712,2025-11-16,[You’re not crazy. You’re just not getting the...,[nas.io],"[Stop guessing. Start Healing, naturally!, Sto...",2025-11-16,2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],1476126802688462,So You Think You Are Healthy,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 65}]","[Comment QUIZ to get the free link now!, Comme..."
10,468492669268944,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-24,2024-12-28,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 192}]",NaN
11,540462482317039,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-26,2024-12-28,"[{'country': 'SE', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 4}]",NaN
12,927457872686945,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-23,2024-12-24,"[{'country': 'ES', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 10002}]",NaN
13,1118856549901694,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-25,2024-12-28,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 13}]",NaN
14,1149767699841006,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-23,2025-01-04,"[{'country': 'EE', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2229}]",NaN
15,1198154008406828,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-19,2024-12-21,"[{'country': 'EE', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 5213}]",NaN
16,1645469656179516,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-25,2024-12-27,"[{'country': 'IT', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 26032}]",NaN
17,1681368622408808,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-26,2024-12-28,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 8067}]",NaN
18,1699924333908780,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-19,2025-01-01,"[{'country': 'RO', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 74}]",NaN
19,1990654091358510,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-24,2024-12-25,"[{'country': 'CY', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6337}]",NaN
20,659209690345526,2025-10-21,[Discover how to take control of your blood su...,[nas.io],"[Join Our FREE Webinar!, Join Our FREE Webinar...",2025-10-21,2025-10-22,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],694879470385928,No Fuss Health,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 127}]","[Secure your spot today, Secure your spot toda..."
21,1510983603181878,2025-10-21,[Always tired or sleepy after eating? That’s y...,[nas.io],"[Join Our Free Webinar Now!, Join Our Free Web...",2025-10-22,2025-10-28,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],694879470385928,No Fuss Health,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 122}]","[Save your seat — Limited slots remaining, Sav..."
22,573867262268518,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],[Chronic Overthinking Test 👉],2024-12-23,2025-02-22,"[{'country': 'MQ', 'age_gender_breakdowns': [{...",[en],214946655027813,Your Personal Coach Sophia,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 18506}]",NaN
23,1238312724100050,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],"[Chronic Overthinking Test 👉, Chronic Overthin...",2024-12-23,2024-12-27,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],214946655027813,Your Personal Coach Sophia,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 1935}]",NaN
24,1266941774632571,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],[Chronic Overthinking Test 👉],2024-12-23,2024-12-26,"[{'country': 'NL', 'age_gender_breakdowns': [{...",[en],213571821842759,Mindway,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 3002}]",NaN

### ACCESSIBILITY

**OC3: Can the requested data be extracted directly from the ad repository response?**

This item verifies whether the platform ad repository returns structured data on ad creatives and authorship directly in the response, rather than providing a link that redirects to the data. Audiovisual media files and data (e.g., images, videos, and audio) should not be considered when assessing this item. The assessment should examine sample data responses from both the ad repository GUI and API to confirm that the requested public data is included in the returned payload.*

In [16]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,ad_creative_bodies,ad_creative_link_descriptions,ad_creative_link_titles,bylines,page_id,page_name"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET SEARCH TERM
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

,id,ad_creative_bodies,ad_creative_link_titles,page_id,page_name,ad_creative_link_descriptions
0,4192086697717648,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],434190399773378,Enseignement-Apprentissage,NaN
1,566436209821750,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],355127741015217,Real Team,NaN
2,543784622115975,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],100855685416689,Ale Memes esse é o foi,NaN
3,569384776193327,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],109194464742841,UsbonGarrh,NaN
4,1780320716164479,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],105870398554650,Michael EM,NaN
5,708779748236211,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],105774929142171,Malucus,NaN
6,1225703642407613,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],102242762540264,Deus é fiel,NaN
7,990332916558558,"[Tired of dealing with thick, yellow, brittle ...",[Take control of your nail health today],104310028613716,Hustle Nation Team Tubombeko,NaN
8,1256665679256719,[Login to get free summons😍\nGift Code: vip888🎁],[🎮 Join now and get 1000 summons FREE!],126004137251949,Courage Evolution·ⅷ,NaN
9,2029047231250712,[You’re not crazy. You’re just not getting the...,"[Stop guessing. Start Healing, naturally!, Sto...",1476126802688462,So You Think You Are Healthy,"[Comment QUIZ to get the free link now!, Comme..."
10,468492669268944,[Effecto.app helps people take control of ADHD...,[Rewire Your ADHD Brain & Unlock Your Potential],101597769428483,Effecto,NaN
11,540462482317039,[Effecto.app helps people take control of ADHD...,[Rewire Your ADHD Brain & Unlock Your Potential],101597769428483,Effecto,NaN
12,927457872686945,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[Grab your plan for 51% OFF!],351656754687509,Top 5 apps for ADHD,NaN
13,1118856549901694,[Effecto.app helps people take control of ADHD...,[Rewire Your ADHD Brain & Unlock Your Potential],101597769428483,Effecto,NaN
14,1149767699841006,[Effecto.app helps people take control of ADHD...,[Rewire Your ADHD Brain & Unlock Your Potential],101597769428483,Effecto,NaN
15,1198154008406828,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[Grab your plan for 51% OFF!],351656754687509,Top 5 apps for ADHD,NaN
16,1645469656179516,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[Grab your plan for 51% OFF!],351656754687509,Top 5 apps for ADHD,NaN
17,1681368622408808,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[Grab your plan for 51% OFF!],351656754687509,Top 5 apps for ADHD,NaN
18,1699924333908780,[Effecto.app helps people take control of ADHD...,[Rewire Your ADHD Brain & Unlock Your Potential],101597769428483,Effecto,NaN
19,1990654091358510,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[Grab your plan for 51% OFF!],351656754687509,Top 5 apps for ADHD,NaN
20,659209690345526,[Discover how to take control of your blood su...,"[Join Our FREE Webinar!, Join Our FREE Webinar...",694879470385928,No Fuss Health,"[Secure your spot today, Secure your spot toda..."
21,1510983603181878,[Always tired or sleepy after eating? That’s y...,"[Join Our Free Webinar Now!, Join Our Free Web...",694879470385928,No Fuss Health,"[Save your seat — Limited slots remaining, Sav..."
22,573867262268518,[✨️️️️️️️ Stop overthinking and start living t...,[Chronic Overthinking Test 👉],214946655027813,Your Personal Coach Sophia,NaN
23,1238312724100050,[✨️️️️️️️ Stop overthinking and start living t...,"[Chronic Overthinking Test 👉, Chronic Overthin...",214946655027813,Your Personal Coach Sophia,NaN
24,1266941774632571,[✨️️️️️️️ Stop overthinking and start living t...,[Chronic Overthinking Test 👉],213571821842759,Mindway,NaN

In [17]:
if response["data"]:
    URL_PATTERN = r"https?://\S+"
    df = pd.DataFrame(response["data"])
    schema = pa.DataFrameSchema(
        columns={},
        checks=pa.Check(
            lambda df: (
                df.select_dtypes(include=['object'])
                .apply(lambda s: s.str.contains(URL_PATTERN).any(), axis=0)
                .sum() == 0
            ),
            name="DirectResponse"
        ),
        strict=False 
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: No links found in any ad creative or authorship column.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Links are present in ad creatives or authorship columns.")
        print(err)

✅ Validation Successful: No links found in any ad creative or authorship column.

**OC5: Can data from an individual ad be retrieved from the platform?**

*This item verifies whether it is possible to retrieve data from a specific advertisement on the ad repository using a unique identifier, rather than relying on search terms or other parameters and filters. The assessment should review the ad repository documentation and test available features to confirm that an individual ad can be retrieved directly by its unique identifier.*

Ad Library link: [AD ID](https://www.facebook.com/ads/library/?id=794155346789288)

In [18]:
# Use this cell to develop an example where a request for ads from a campaign is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
ad_id = '794155346789288' # SET VALUE HERE
fields="id"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": ad_id,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    found_ad = False
    for ad in response["data"]:
        if ad["id"] == ad_id:
            found_ad = True
            break
    if found_ad:
        print(f"Found ad {ad_id} in response")
        print(response)
    else:
        print(f"Ad {ad_id} not found in response")
        print(response)
else:
    print("No data were found in response")
    print(response)

Ad 794155346789288 not found in response
{'data': []}

In [19]:
ad_id = '25547504004847190' # SET AD ID
fields="id"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_page_ids": ad_id,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    found_ad = False
    for ad in response["data"]:
        if ad["id"] == ad_id:
            found_ad = True
            break
    if found_ad:
        print(f"Found ad {ad_id} in response")
        print(response)
    else:
        print(f"Ad {ad_id} not found in response")
        print(response)
else:
    print("No data were found in response")
    print(response)

Ad 25547504004847190 not found in response
{'data': []}

**OC6: Can data from ads served by a specific advertiser be retrieved from the platform?**

*This item verifies whether it is possible to retrieve data from ads run by a specific advertiser, via their username or unique identifier. The assessment should review the ad repository documentation and test any available feature to retrieve data from an individual advertiser.*

In [20]:
# Use this cell to develop an example where a request for ads from an advertiser is made.
# Please leave the result as the output of this cell.
advertiser = '434190399773378' # SET VALUE
fields="id,page_id,page_name"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_page_ids": advertiser,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    found_advertiser = False
    other_advertisers = 0
    for ad in response["data"]:
        if ad["page_id"] == advertiser:
            found_advertiser = True
        else:
            other_advertisers += 1
    if found_advertiser and other_advertisers == 0:
        print(f"Only ads from advertiser {advertiser} were found in response")
    elif found_advertiser and other_advertisers > 0:
        print(f"Found ads from advertiser {advertiser} and {other_advertisers} others in response")
    else:
        print(f"Advertiser {advertiser} not found in response")
else:
    print("No data were found in response")
    print(response)

Only ads from advertiser 434190399773378 were found in response

**OC7: Can ad data be retrieved from the platform using search terms?**

*This item verifies whether data on ad campaigns can be retrieved via individual or combined search terms, enabling the creation of a dataset composed of ads that mention those terms. The assessment should test search-related features to confirm that queries using keywords return relevant ad campaign data.*

In [21]:
# Use this cell to develop an example where a request for ads is made using a search term.
# Please leave the result as the output of this cell.
search_term = "health" # SET THE VALUE HERE
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": search_term,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request using the search term {search_term}")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request using the search term health

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,languages,page_id,page_name,publisher_platforms,target_ages,target_gender,target_locations,total_reach_by_location,ad_creative_link_descriptions
0,4192086697717648,2025-05-05,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-05,2025-05-05,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],434190399773378,Enseignement-Apprentissage,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 36}]",NaN
1,566436209821750,2025-05-05,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-05,2025-05-06,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],355127741015217,Real Team,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 11}]",NaN
2,543784622115975,2025-05-03,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-04,2025-05-04,"[{'country': 'FI', 'age_gender_breakdowns': [{...",[en],100855685416689,Ale Memes esse é o foi,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2}]",NaN
3,569384776193327,2025-05-03,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-03,2025-05-06,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],109194464742841,UsbonGarrh,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Austria', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 181}]",NaN
4,1780320716164479,2025-05-02,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-05-02,2025-05-03,"[{'country': 'FI', 'age_gender_breakdowns': [{...",[en],105870398554650,Michael EM,"[facebook, audience_network]","[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6}]",NaN
5,708779748236211,2025-04-30,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-30,2025-05-01,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],105774929142171,Malucus,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 9}]",NaN
6,1225703642407613,2025-04-30,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-30,2025-05-03,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],102242762540264,Deus é fiel,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 75}]",NaN
7,990332916558558,2025-04-27,"[Tired of dealing with thick, yellow, brittle ...",[emscomfy.com],[Take control of your nail health today],2025-04-27,2025-04-29,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],104310028613716,Hustle Nation Team Tubombeko,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 1}]",NaN
8,1256665679256719,2025-07-31,[Login to get free summons😍\nGift Code: vip888🎁],[itunes.apple.com],[🎮 Join now and get 1000 summons FREE!],2025-08-01,2025-08-03,"[{'country': 'DE', 'age_gender_breakdowns': [{...",NaN,126004137251949,Courage Evolution·ⅷ,"[facebook, instagram, audience_network, messen...","[21, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 8}, {'key': 'GB', 'val...",NaN
9,2029047231250712,2025-11-16,[You’re not crazy. You’re just not getting the...,[nas.io],"[Stop guessing. Start Healing, naturally!, Sto...",2025-11-16,2025-11-17,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],1476126802688462,So You Think You Are Healthy,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 65}]","[Comment QUIZ to get the free link now!, Comme..."
10,468492669268944,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-24,2024-12-28,"[{'country': 'PT', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 192}]",NaN
11,540462482317039,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-26,2024-12-28,"[{'country': 'SE', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 4}]",NaN
12,927457872686945,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-23,2024-12-24,"[{'country': 'ES', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 10002}]",NaN
13,1118856549901694,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-25,2024-12-28,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 13}]",NaN
14,1149767699841006,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-23,2025-01-04,"[{'country': 'EE', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2229}]",NaN
15,1198154008406828,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-19,2024-12-21,"[{'country': 'EE', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 5213}]",NaN
16,1645469656179516,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-25,2024-12-27,"[{'country': 'IT', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 26032}]",NaN
17,1681368622408808,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-26,2024-12-28,"[{'country': 'FR', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 8067}]",NaN
18,1699924333908780,2024-12-19,[Effecto.app helps people take control of ADHD...,[effecto.app],[Rewire Your ADHD Brain & Unlock Your Potential],2024-12-19,2025-01-01,"[{'country': 'RO', 'age_gender_breakdowns': [{...",[en],101597769428483,Effecto,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 74}]",NaN
19,1990654091358510,2024-12-19,[⭐⭐⭐⭐⭐\nLike Flo but for ADHD\n🌱 Find your ult...,[effecto.app],[Grab your plan for 51% OFF!],2024-12-24,2024-12-25,"[{'country': 'CY', 'age_gender_breakdowns': [{...",[en],351656754687509,Top 5 apps for ADHD,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6337}]",NaN
20,659209690345526,2025-10-21,[Discover how to take control of your blood su...,[nas.io],"[Join Our FREE Webinar!, Join Our FREE Webinar...",2025-10-21,2025-10-22,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],694879470385928,No Fuss Health,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 127}]","[Secure your spot today, Secure your spot toda..."
21,1510983603181878,2025-10-21,[Always tired or sleepy after eating? That’s y...,[nas.io],"[Join Our Free Webinar Now!, Join Our Free Web...",2025-10-22,2025-10-28,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],694879470385928,No Fuss Health,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 122}]","[Save your seat — Limited slots remaining, Sav..."
22,573867262268518,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],[Chronic Overthinking Test 👉],2024-12-23,2025-02-22,"[{'country': 'MQ', 'age_gender_breakdowns': [{...",[en],214946655027813,Your Personal Coach Sophia,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 18506}]",NaN
23,1238312724100050,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],"[Chronic Overthinking Test 👉, Chronic Overthin...",2024-12-23,2024-12-27,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],214946655027813,Your Personal Coach Sophia,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 1935}]",NaN
24,1266941774632571,2024-12-19,[✨️️️️️️️ Stop overthinking and start living t...,[mindway.app],[Chronic Overthinking Test 👉],2024-12-23,2024-12-26,"[{'country': 'NL', 'age_gender_breakdowns': [{...",[en],213571821842759,Mindway,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 3002}]",NaN

**OC8: Does the platform use locale-neutral data representations?**

*This item verifies whether locale-sensitive data (e.g., timestamps, currency, numbers) are provided in a locale-neutral format, or, if that is not possible, whether relevant locale metadata is included. The assessment should review the ad repository documentation and inspect sample responses to confirm the presence of standardized formats or accompanying metadata.*

In [22]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
query = "health" # SET VALUE
fields="id,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,currency"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

,id,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time
0,4192086697717648,2025-05-05,2025-05-05,2025-05-05
1,566436209821750,2025-05-05,2025-05-05,2025-05-06
2,543784622115975,2025-05-03,2025-05-04,2025-05-04
3,569384776193327,2025-05-03,2025-05-03,2025-05-06
4,1780320716164479,2025-05-02,2025-05-02,2025-05-03
5,708779748236211,2025-04-30,2025-04-30,2025-05-01
6,1225703642407613,2025-04-30,2025-04-30,2025-05-03
7,990332916558558,2025-04-27,2025-04-27,2025-04-29
8,1256665679256719,2025-07-31,2025-08-01,2025-08-03
9,2029047231250712,2025-11-16,2025-11-16,2025-11-17
10,468492669268944,2024-12-19,2024-12-24,2024-12-28
11,540462482317039,2024-12-19,2024-12-26,2024-12-28
12,927457872686945,2024-12-19,2024-12-23,2024-12-24
13,1118856549901694,2024-12-19,2024-12-25,2024-12-28
14,1149767699841006,2024-12-19,2024-12-23,2025-01-04
15,1198154008406828,2024-12-19,2024-12-19,2024-12-21
16,1645469656179516,2024-12-19,2024-12-25,2024-12-27
17,1681368622408808,2024-12-19,2024-12-26,2024-12-28
18,1699924333908780,2024-12-19,2024-12-19,2025-01-01
19,1990654091358510,2024-12-19,2024-12-24,2024-12-25
20,659209690345526,2025-10-21,2025-10-21,2025-10-22
21,1510983603181878,2025-10-21,2025-10-22,2025-10-28
22,573867262268518,2024-12-19,2024-12-23,2025-02-22
23,1238312724100050,2024-12-19,2024-12-23,2024-12-27
24,1266941774632571,2024-12-19,2024-12-23,2024-12-26

In [23]:
if "data" in response:
    df = pd.json_normalize(response["data"])
    df["ad_creation_time"] = pd.to_datetime( df["ad_creation_time"])
    df["ad_delivery_start_time"] = pd.to_datetime( df["ad_delivery_start_time"])
    df["ad_delivery_stop_time"] = pd.to_datetime( df["ad_delivery_stop_time"])
    schema = pa.DataFrameSchema(
        {
            "ad_creation_time": pa.Column(
                pa.DateTime, 
                nullable=True, 
                title="Ad creation time"
            ),
            "ad_delivery_start_time": pa.Column(
                pa.DateTime, 
                nullable=False, 
                title="Ad delivery start time"
            ),
            "ad_delivery_stop_time": pa.Column(
                pa.DateTime, 
                nullable=True, 
                title="Ad delivery stop time"
            ),
            "currency": pa.Column(
                pa.String,
                pa.Check.equal_to("GBP"), 
                nullable=False, 
                title="Currency"
            ),
        
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: Data is locale-neutral represented.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Data is not locale-neutral represented.")
        print(err)

❌ Validation Failed: Data is not locale-neutral represented.
{
    "SCHEMA": {
        "COLUMN_NOT_IN_DATAFRAME": [
            {
                "schema": null,
                "column": null,
                "check": "column_in_dataframe",
                "error": "column 'currency' not in dataframe. Columns in dataframe: ['id', 'ad_creation_time', 'ad_delivery_start_time', 'ad_delivery_stop_time']"
            }
        ]
    }
}

In [24]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
query = "health" # SET VALUE
fields="id,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,currency"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

,id,ad_creation_time,ad_delivery_start_time,currency,ad_delivery_stop_time
0,820201220997208,2025-11-17,2025-11-18,GBP,NaN
1,2304576016640979,2025-11-17,2025-11-17,GBP,NaN
2,1471437670627318,2025-11-17,2025-11-17,GBP,2025-11-17
3,2355445218205574,2025-11-17,2025-11-17,EUR,2025-11-18
4,1583691626406370,2025-11-17,2025-11-17,GBP,NaN
5,1158136649632381,2025-11-17,2025-11-17,GBP,NaN
6,766996016361133,2025-11-17,2025-11-17,GBP,NaN
7,1506911813892989,2025-11-17,2025-11-17,GBP,NaN
8,4072423809674987,2025-11-17,2025-11-17,CHF,2025-11-18
9,1201738788490856,2025-11-17,2025-11-17,GBP,NaN
10,1018345883784718,2025-11-17,2025-11-17,GBP,2025-11-18
11,25547504004847190,2025-11-16,2025-11-16,GBP,2025-11-17
12,865891392528045,2025-11-16,2025-11-16,UAH,2025-11-18
13,869895502220383,2025-11-16,2025-11-16,UAH,2025-11-16
14,2702739236731672,2025-11-16,2025-11-16,GBP,2025-11-18
15,4075866789347012,2025-11-15,2025-11-15,GBP,2025-11-16
16,1491394831915817,2025-11-15,2025-11-15,GBP,NaN
17,1368507788086212,2025-11-15,2025-11-15,GBP,NaN
18,853565240499142,2025-11-15,2025-11-15,GBP,2025-11-16
19,766947929732943,2025-11-14,2025-11-14,GBP,2025-11-16
20,846137747884428,2025-11-14,2025-11-14,GBP,2025-11-17
21,1864870594445656,2025-11-14,2025-11-14,GBP,NaN
22,4307252356177172,2025-11-14,2025-11-14,GBP,NaN
23,2024356928405238,2025-11-14,2025-11-14,GBP,NaN
24,3762748727354087,2025-11-14,2025-11-14,GBP,NaN

In [25]:
if "data" in response:
    df = pd.json_normalize(response["data"])
    df["ad_creation_time"] = pd.to_datetime( df["ad_creation_time"])
    df["ad_delivery_start_time"] = pd.to_datetime( df["ad_delivery_start_time"])
    df["ad_delivery_stop_time"] = pd.to_datetime( df["ad_delivery_stop_time"])
    schema = pa.DataFrameSchema(
        {
            "ad_creation_time": pa.Column(
                pa.DateTime, 
                nullable=True, 
                title="Ad creation time"
            ),
            "ad_delivery_start_time": pa.Column(
                pa.DateTime, 
                nullable=False, 
                title="Ad delivery start time"
            ),
            "ad_delivery_stop_time": pa.Column(
                pa.DateTime, 
                nullable=True, 
                title="Ad delivery stop time"
            ),
            "currency": pa.Column(
                pa.String,
                pa.Check.equal_to("GBP"), 
                nullable=False, 
                title="Currency"
            ),
        
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: Data is locale-neutral represented.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Data is not locale-neutral represented.")
        print(err)

❌ Validation Failed: Data is not locale-neutral represented.
{
    "DATA": {
        "DATAFRAME_CHECK": [
            {
                "schema": null,
                "column": "currency",
                "check": "equal_to(GBP)",
                "error": "Column 'currency' failed element-wise validator number 0: equal_to(GBP) failure cases: EUR, CHF, UAH, UAH"
            }
        ]
    }
}

### COMPLETENESS

**OC9: Does the platform provide data that allows the identification of advertisers who ran ads?**

*This item verifies whether the platform discloses information on the advertisers responsible for the identified ads. The assessment should confirm whether the advertiser’s page name, URL, and unique identifier can be retrieved.*

In [28]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
query = "*" # SET VALUE
fields="id,page_id,page_name"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

,id,page_id,page_name
0,2166638110526249,865055823360582,Shoping House
1,1163464415972432,891656217359413,Sumono Shop
2,1604973074260846,371478356677753,Josef Vitzthum
3,1374939944342996,105920594096267,Вакум хаалга цонх засвар / vakum tsonkh zasvar...
4,3193648980809479,216707358190376,Arttaib
5,823238210316661,102854402460581,FiberOne Boats
6,1483626042723309,103858342483163,Zee Big Apple Motors
7,1530792554727145,103858342483163,Zee Big Apple Motors
8,1369911991288823,103858342483163,Zee Big Apple Motors
9,1106852878283096,578775288662683,Express Moving Inc.
10,2141262403069070,578775288662683,Express Moving Inc.
11,1163795772362612,578775288662683,Express Moving Inc.
12,1924140148483105,578775288662683,Express Moving Inc.
13,4107188869532163,578775288662683,Express Moving Inc.
14,3236978256457623,578775288662683,Express Moving Inc.
15,1391228535859802,578775288662683,Express Moving Inc.
16,1184246100216409,578775288662683,Express Moving Inc.
17,1532804798138818,578775288662683,Express Moving Inc.
18,774201922120677,102935771439130,Rodeo grill
19,1347824223655719,578775288662683,Express Moving Inc.
20,2335273510220113,112601008413046,البيت السعيد - ولاية وهران -
21,1496843104905560,754110104444651,Nusa Properti Dea
22,4175734039306313,754110104444651,Nusa Properti Dea
23,4194606820760610,100605691559395,BD Jobs Solution
24,1363407165492039,216969501503429,Shoping.day

In [29]:
if "data" in response:
    df = pd.DataFrame(response["data"])
    schema = pa.DataFrameSchema(
        {
            "page_id": pa.Column(
                pa.String, 
                nullable=False,  
                title="Page Id"
            ),
            "page_name": pa.Column(
                pa.String, 
                nullable=False,   
                title="Page Name"
            ),
        
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: Advertisers information columns are present and non-null.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing advertisers information.")
        print(err)

✅ Validation Successful: Advertisers information columns are present and non-null.

**OC10: Does the platform provide data on the funders who paid for ads?**

*This item verifies whether the platform provides data on who paid for ad campaigns. The assessment should confirm whether any sponsor information can be retrieved.*

In [35]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
query = "health" # SET VALUE
fields="id,bylines"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": False
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

                  id
0   4192086697717648
1    566436209821750
2    543784622115975
3    569384776193327
4   1780320716164479
5    708779748236211
6   1225703642407613
7    990332916558558
8   1256665679256719
9   2029047231250712
10   468492669268944
11   540462482317039
12   927457872686945
13  1118856549901694
14  1149767699841006
15  1198154008406828
16  1645469656179516
17  1681368622408808
18  1699924333908780
19  1990654091358510
20   659209690345526
21  1510983603181878
22   573867262268518
23  1238312724100050
24  1266941774632571

In [36]:
if "data" in response:
    df = pd.DataFrame(response["data"])
    schema = pa.DataFrameSchema(
        {
            "bylines": pa.Column(
                pa.String, 
                nullable=False,  
                title="Bylines"
            )
        
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: Funders information columns are present and non-null.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing funders information.")
        print(err)

❌ Validation Failed: Missing funders information.
{
    "SCHEMA": {
        "COLUMN_NOT_IN_DATAFRAME": [
            {
                "schema": null,
                "column": null,
                "check": "column_in_dataframe",
                "error": "column 'bylines' not in dataframe. Columns in dataframe: ['id']"
            }
        ]
    }
}

In [33]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
query = "health" # SET VALUE
fields="id,bylines"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": False
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

                   id                                            bylines
0     820201220997208                                   Railway Children
1    2304576016640979  Midlothian South, Tweeddale and Lauderdale Con...
2    1471437670627318  Midlothian South, Tweeddale and Lauderdale Con...
3    2355445218205574                                                NaN
4    1583691626406370  Médecins Sans Frontières / Doctors Without Bor...
5    1158136649632381                                Action For Humanity
6     766996016361133                                Action For Humanity
7    1506911813892989                                Action For Humanity
8    4072423809674987                                                NaN
9    1201738788490856    Re-Elect Christina McAnea for General Secretary
10   1018345883784718                                                NaN
11  25547504004847190                                                NaN
12    865891392528045                                                NaN
13    869895502220383                                                NaN
14   2702739236731672                             GRASS Cliftonville CIC
15   4075866789347012                                                NaN
16   1491394831915817                        National Emergency Briefing
17   1368507788086212                                      Zen Ghani SNP
18    853565240499142                             GRASS Cliftonville CIC
19    766947929732943                                                NaN
20    846137747884428    Re-Elect Christina McAnea for General Secretary
21   1864870594445656    Re-Elect Christina McAnea for General Secretary
22   4307252356177172                                      Muslim Relief
23   2024356928405238                           Welsh Conservative Party
24   3762748727354087                         Warrington Borough Council

In [34]:
if "data" in response:
    df = pd.DataFrame(response["data"])
    schema = pa.DataFrameSchema(
        {
            "bylines": pa.Column(
                pa.String, 
                nullable=False,  
                title="Bylines"
            )
        
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: Funders information columns are present and non-null.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing funders information.")
        print(err)

❌ Validation Failed: Missing funders information.
{
    "SCHEMA": {
        "SERIES_CONTAINS_NULLS": [
            {
                "schema": null,
                "column": "bylines",
                "check": "not_nullable",
                "error": "non-nullable series 'bylines' contains null values:3     NaN8     NaN10    NaN11    NaN12    NaN13    NaN15    NaN19    NaNName: bylines, dtype: object"
            }
        ]
    }
}

**OC11: Does the platform provide data on the period during which ads were served?**

*This item verifies whether the platform provides data on the days on which ad campaigns ran. The assessment should review ad records to confirm that campaigns include start and end dates (or equivalent temporal markers) covering their active period*

In [37]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
query = "health" # SET VALUE
fields="id,ad_delivery_start_time,ad_delivery_stop_time"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "INACTIVE",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

                  id ad_delivery_start_time ad_delivery_stop_time
0   4192086697717648             2025-05-05            2025-05-05
1    566436209821750             2025-05-05            2025-05-06
2    543784622115975             2025-05-04            2025-05-04
3    569384776193327             2025-05-03            2025-05-06
4   1780320716164479             2025-05-02            2025-05-03
5    708779748236211             2025-04-30            2025-05-01
6   1225703642407613             2025-04-30            2025-05-03
7    990332916558558             2025-04-27            2025-04-29
8   1256665679256719             2025-08-01            2025-08-03
9   2029047231250712             2025-11-16            2025-11-17
10   468492669268944             2024-12-24            2024-12-28
11   540462482317039             2024-12-26            2024-12-28
12   927457872686945             2024-12-23            2024-12-24
13  1118856549901694             2024-12-25            2024-12-28
14  1149767699841006             2024-12-23            2025-01-04
15  1198154008406828             2024-12-19            2024-12-21
16  1645469656179516             2024-12-25            2024-12-27
17  1681368622408808             2024-12-26            2024-12-28
18  1699924333908780             2024-12-19            2025-01-01
19  1990654091358510             2024-12-24            2024-12-25
20   659209690345526             2025-10-21            2025-10-22
21  1510983603181878             2025-10-22            2025-10-28
22   573867262268518             2024-12-23            2025-02-22
23  1238312724100050             2024-12-23            2024-12-27
24  1266941774632571             2024-12-23            2024-12-26

In [38]:
if "data" in response:
    df = pd.DataFrame(response["data"])
    df["ad_delivery_start_time"] = pd.to_datetime(df["ad_delivery_start_time"])
    df["ad_delivery_stop_time"] = pd.to_datetime(df["ad_delivery_stop_time"])
    schema = pa.DataFrameSchema(
        {
            "ad_delivery_start_time": pa.Column(
                pa.DateTime, 
                nullable=False,  
                title="Ad delivery start time"
            ),
            "ad_delivery_stop_time": pa.Column(
                pa.DateTime, 
                nullable=False,  
                title="Ad delivery stop time"
            )
        
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: Ads' run period dates are present and non-null.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing ads' run period dates.")
        print(err)

✅ Validation Successful: Ads' run period dates are present and non-null.

**OC12: Does the platform provide data on user engagement with ads?**

*This item verifies whether the platform provides data on the total number of user interactions with ad campaigns (e.g., likes, comments, shares, clicks). The assessment should review ad records to confirm that engagement metrics are available and clearly linked to each campaign.*

There's no field to retrieve user interactions. A complete list of available fields can be found in: https://developers.facebook.com/docs/graph-api/reference/archived-ad/

**OC13: Does the platform indicate whether ads were placed by verified or unverified advertisers?**

*This item verifies whether the platform clearly indicates whether advertisers were verified at the time their ads were served. The assessment should review ad records to confirm that a verification status field is present.*

There's no field that indicates if a advertiser is verified. A complete list of available fields can be found in: https://developers.facebook.com/docs/graph-api/reference/archived-ad/

### COMPLIANCE

**OC14: Does the platform flag ads that were removed due to violations of its guidelines or relevant legislation?**

*This item verifies whether the platform indicates when an ad has been moderated. At a minimum, the platform should provide the reason for removal and the date. The assessment should review ad records to confirm that moderated ads are flagged and that the corresponding moderation details are clearly documented.*

In [58]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
query = "*" # SET VALUE
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            'search_page_ids' : ['103858342483163'],
            "search_terms": query,
            "unmask_removed_content": True # unmask set to TRUE
        }
response = request_to_api(session, payload, api_url)
df = pd.DataFrame(response["data"])
display(df)

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,languages,page_id,page_name,publisher_platforms,target_ages,target_gender,target_locations,total_reach_by_location
0,1483626042723309,2025-11-02,[🚗 For true gearheads only.\nThe CISON Small-b...,[globalshopspot.com],"[🛒 2,519 sold in 24h – grab yours now!]",[🔥BLACK FRIDAY BLOWOUT: Save 49%],2025-11-08,2025-11-08,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],103858342483163,Zee Big Apple Motors,"[facebook, instagram, audience_network, messen...","[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 9}]"
1,1530792554727145,2025-11-01,[🚗 For true gearheads only.\nThe CISON Small-b...,[globalshopspot.com],"[🛒 2,519 sold in 24h – grab yours now!]",[🔥BLACK FRIDAY BLOWOUT: Save 49%],2025-11-02,2025-11-13,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],103858342483163,Zee Big Apple Motors,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 555}]"
2,1369911991288823,2025-10-29,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,2025-11-02,2025-11-08,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],103858342483163,Zee Big Apple Motors,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 3111}]"
3,3436970029791139,2025-11-12,NaN,[facebook.com],NaN,[Zee Big Apple Motors],2025-11-15,2025-11-16,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 25}]"
4,831927239201370,2025-11-01,NaN,[facebook.com],NaN,[Zee Big Apple Motors],2025-11-05,2025-11-08,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 44}]"
5,1262254949275807,2025-10-31,NaN,[facebook.com],NaN,[Zee Big Apple Motors],2025-11-07,2025-11-09,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 20}]"
6,847215507832384,2025-10-28,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,2025-11-01,2025-11-03,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 136}]"

In [ ]:
query = "*" # SET VALUE
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            'search_page_ids' : ['103858342483163'],
            "search_terms": query,
            "unmask_removed_content": False # unmask set to FALSE
        }
response = request_to_api(session, payload, api_url)
df = pd.DataFrame(response["data"])
display(df)

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,languages,page_id,page_name,publisher_platforms,target_ages,target_gender,target_locations,total_reach_by_location
0,1483626042723309,2025-11-02,[🚗 For true gearheads only.\nThe CISON Small-b...,[globalshopspot.com],"[🛒 2,519 sold in 24h – grab yours now!]",[🔥BLACK FRIDAY BLOWOUT: Save 49%],2025-11-08,2025-11-08,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],103858342483163,Zee Big Apple Motors,"[facebook, instagram, audience_network, messen...","[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 9}]"
1,1530792554727145,2025-11-01,[🚗 For true gearheads only.\nThe CISON Small-b...,[globalshopspot.com],"[🛒 2,519 sold in 24h – grab yours now!]",[🔥BLACK FRIDAY BLOWOUT: Save 49%],2025-11-02,2025-11-13,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],103858342483163,Zee Big Apple Motors,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 555}]"
2,1369911991288823,2025-10-29,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,2025-11-02,2025-11-08,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],103858342483163,Zee Big Apple Motors,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 3111}]"
3,3436970029791139,2025-11-12,NaN,[facebook.com],NaN,[Zee Big Apple Motors],2025-11-15,2025-11-16,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 25}]"
4,831927239201370,2025-11-01,NaN,[facebook.com],NaN,[Zee Big Apple Motors],2025-11-05,2025-11-08,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 44}]"
5,1262254949275807,2025-10-31,NaN,[facebook.com],NaN,[Zee Big Apple Motors],2025-11-07,2025-11-09,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 20}]"
6,847215507832384,2025-10-28,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,[This ad was run by an account or Page we late...,2025-11-01,2025-11-03,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,103858342483163,Zee Big Apple Motors,[facebook],"[25, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 136}]"

**OC15: Does the platform indicate whether ad creatives were generated using artificial intelligence?**

*This item verifies whether the platform flags ad campaigns in which AI played a role in producing the content. The assessment should review ad records to confirm the presence of a field or label indicating the use of AI in ad production.*

There's no field that indicates if an ad was created using AI. A complete list of available fields can be found in: https://developers.facebook.com/docs/graph-api/reference/archived-ad/

### CONSISTENCY

**OC23: Does the data retrieved by the API reflect what is displayed on the platform’s ad repository GUI?**

*This item verifies whether the data returned by the platform’s ad repository API corresponds to the information displayed on its GUI in all its levels of detail. It should be possible to identify in the API response information such as authorship, complete content, and other campaigning information (e.g., amount spent, impressions reached). The assessment should compare API responses with the GUI to confirm that key elements—such as authorship, full content, and campaign information (e.g., spending, impressions)—are consistently included.*

In [60]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
page_id = "678851558858294" # SET VALUE
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_page_ids": page_id,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
print(response["data"][0])

{'id': '667790906185052', 'ad_creation_time': '2025-10-31', 'ad_creative_bodies': ['The Surrey Half Marathon will take place on the 22nd March 2026. Sign up today and run for mental health research!', 'The Surrey Half Marathon will take place on the 22nd March 2026. Sign up today and run for mental health research!'], 'ad_creative_link_captions': ['fb.me'], 'ad_creative_link_descriptions': ['Run for mental health research', 'Run for mental health research'], 'ad_creative_link_titles': ['Raise Money For Mental Health Research', 'Raise Money For Mental Health Research'], 'ad_delivery_start_time': '2025-11-17', 'age_country_gender_reach_breakdown': [{'country': 'GB', 'age_gender_breakdowns': [{'age_range': '18-24', 'male': 50, 'female': 43, 'unknown': 1}, {'age_range': '25-34', 'male': 109, 'female': 65, 'unknown': 1}, {'age_range': '35-44', 'male': 133, 'female': 64, 'unknown': 2}, {'age_range': '45-54', 'male': 59, 'female': 29, 'unknown': 3}]}], 'languages': ['en'], 'page_id': '678851558858294', 'page_name': 'MQ Mental Health Research', 'publisher_platforms': ['facebook', 'instagram', 'audience_network'], 'target_ages': ['19', '51'], 'target_gender': 'All', 'target_locations': [{'name': 'Crawley, United Kingdom', 'num_obfuscated': 0, 'type': 'CITY', 'excluded': False}, {'name': 'Guildford, United Kingdom', 'num_obfuscated': 0, 'type': 'CITY', 'excluded': False}, {'name': 'London, United Kingdom', 'num_obfuscated': 0, 'type': 'CITY', 'excluded': False}, {'name': 'Reading, United Kingdom', 'num_obfuscated': 0, 'type': 'CITY', 'excluded': False}], 'total_reach_by_location': [{'key': 'GB', 'value': 561}]}

**OC24: Are the results returned by the platform consistently reproducible?**


*This item verifies whether data accessed and extracted via the platform’s ad repository at a given time is consistent with other collections performed similarly, including cases where content was deleted in the interim. The assessment should perform repeated queries to confirm reproducibility of results.*

Test instructions: Please, develop a test that collects ads for 5 times using the same request parameters and the same endpoint. Save each response in separate files.

In [69]:
# Use this cell, or more, to develop a process that collects ads more than one time using the same request parameters.
# Describe the endpoint and the search parameters used.
# Please add each response for each time a request is made in a file and save it in the data folder of this repository.
# The files naming pattern should be as stated below:
total_runs = 5 
for idx in range(total_runs):
    sleep(10)
    index = idx + 1
    timestamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S-%f")
    filename = f"uk-meta-ads-question-24-run-{index}-{timestamp}"

    fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
    api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
    query = "health" # SET VALUE
    payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
    response = request_to_api(session, payload, api_url)

    outfile = os.path.join(FILEPATH, f"{filename}.json")

    with open(outfile, "w") as fout:
        json.dump(response, fout)

In [70]:
# Read files here to compare
pattern = os.path.join(FILEPATH, "uk-meta-ads-question-24*")
files = sorted(glob.glob(pattern))
all_files = []
for idx, file in enumerate(files):
    with open(file) as fin:
        data = json.load(fin)
    df = pd.DataFrame(data["data"])
    df["filename"] = os.path.basename(file)
    all_files.append(df)
df_complete = pd.concat(all_files, ignore_index=True)
df_agg = df_complete.groupby("id").agg(total_occurance=("id", "count"),first_occurance_file=("filename", "min"), last_occurance_file=("filename", "max"),start_delivery_date_max=("ad_delivery_start_time", "max"))
display(df_agg)

,total_occurance,first_occurance_file,last_occurance_file,start_delivery_date_max
id,,,,
1118856549901694,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-25
1149767699841006,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-23
1198154008406828,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-19
1225703642407613,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-04-30
1238312724100050,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-23
1256665679256719,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-08-01
1266941774632571,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-23
1510983603181878,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-10-22
1645469656179516,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-25
1681368622408808,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-26
1699924333908780,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-19
1780320716164479,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-05-02
1990654091358510,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-24
2029047231250712,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-11-16
4192086697717648,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-05-05
468492669268944,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-24
540462482317039,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-26
543784622115975,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-05-04
566436209821750,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-05-05
569384776193327,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-05-03
573867262268518,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-23
659209690345526,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-10-21
708779748236211,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-04-30
927457872686945,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2024-12-23
990332916558558,5,uk-meta-ads-question-24-run-1-2025-11-18T14-55...,uk-meta-ads-question-24-run-5-2025-11-18T14-56...,2025-04-27

**OC25: Is the data returned by the platform consistent with the parameters and filters used in the request?**

*This item verifies whether the data retrieved through the ad repository accurately reflects the parameters and filters specified at the time of the request. The assessment should run test queries with different filters to confirm that results consistently match the requested conditions.*

Test instructions: Please, develop a process that request data using different parameter to the same endpoint. If possible, test at least 5 different parameters/filters. If the platform provides less than 5, use all available parameters/filters.

Save each response in separate files.

In [102]:
# Use this cell, or more, to develop a process that collects ads more than one time using different parameters.
# Describe the endpoint and the search parameters used.
# Please add each response for each time a request is made in a file and save it in the data folder of this repository.
# The files naming pattern should be as stated below:

#FEEL FREE TO CHANGE PARAMETERS
parameters = [{"ad_delivery_date_min": "2025-11-01"}, 
                {"bylines": ["Labour Future"]}, 
                {"delivery_by_region": ["England"]}, 
                {"estimated_audience_size_min":1000}, 
                {"languages": ["en"]}]
for idx, param in enumerate(parameters):
    sleep(1)
    index = idx + 1 
    timestamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S-%f")
    filename = f"uk-meta-ads-question-25-run-{index}-{list(param.keys())[0]}-{timestamp}"
    
    fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
    api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
    query = "health" # Feel free to change value
    payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "INACTIVE",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
    payload.update(param)
    response = request_to_api(session, payload, api_url)

    with open(f"{FILEPATH}/{filename}.json", "w") as fout:
        json.dump(response, fout)

In [104]:
# ad_delivery_date_min > 2025-11-01
filename = "uk-meta-ads-question-25-run-1-ad_delivery_date_min-2025-11-18T17-22-56-709498.json" # SET VALUE
with open(f"{FILEPATH}/{filename}") as fin:
    data = json.load(fin)
df = pd.DataFrame(data["data"])
df["ad_delivery_start_time"] = pd.to_datetime(df["ad_delivery_start_time"])
df["ad_delivery_stop_time"] = pd.to_datetime(df["ad_delivery_stop_time"])
schema = pa.DataFrameSchema(
    {
        "ad_delivery_stop_time": pa.Column(
            pa.DateTime, 
            checks=pa.Check.greater_than_or_equal_to("2025-11-01"),
            nullable=False,  
            title="Ad delivery start time"
        )
    },
    strict=False
)
try:
    schema.validate(df, lazy=True)
    print("✅ Validation Successful: All ads ran after the set ad_delivery_date_min parameter.")
except SchemaErrors as err:
    print("❌ Validation Failed: Found ads that ran earlier than the set ad_delivery_date_min parameter")
    print(err)

✅ Validation Successful: All ads ran after the set ad_delivery_date_min parameter.

In [105]:
# bylines: Labour Future
filename = "uk-meta-ads-question-25-run-2-bylines-2025-11-18T17-23-00-143281.json" # SET VALUE
with open(f"{FILEPATH}/{filename}") as fin:
    data = json.load(fin)
if "data" in data:
    df = pd.DataFrame(data["data"])

    schema = pa.DataFrameSchema(
        {
            "bylines": pa.Column(
                checks=pa.Check.equal_to("Labour Future"),
                nullable=False,  
                title="Bylines"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have funders information as set in bylines parameter.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Found ads that are not from funders as set in bylines parameter")
        print(err)

✅ Validation Successful: All ads have funders information as set in bylines parameter.

In [106]:
# delivery_by_region: Manchester
def extract_regions(x):
    if isinstance(x, list) and len(x) > 0: 
        return [d['region'] for d in x]
    return x

def check_delivery_region(regions):
    return regions.apply(lambda region_list: "England" in region_list)

filename = "uk-meta-ads-question-25-run-3-delivery_by_region-2025-11-18T17-23-01-844199.json" # SET VALUE
with open(f"{FILEPATH}/{filename}") as fin:
    data = json.load(fin)

if "data" in data:
    df = pd.DataFrame(data["data"])
    df["ad_delivery_regions"] = df["delivery_by_region"].apply(extract_regions)

    schema = pa.DataFrameSchema(
        {
            "ad_delivery_regions": pa.Column(
                checks=pa.Check(check_delivery_region),
                nullable=False,  
                title="Ad delivery regions"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have region information as set in delivery_by_region parameter.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Found ads that don't have or are not from the regions as set in delivery_by_region parameter")
        print(err)

❌ Validation Failed: Found ads that don't have or are not from the regions as set in delivery_by_region parameter
{
    "SCHEMA": {
        "SERIES_CONTAINS_NULLS": [
            {
                "schema": null,
                "column": "ad_delivery_regions",
                "check": "not_nullable",
                "error": "non-nullable series 'ad_delivery_regions' contains null values:1     NaN11    NaN13    NaNName: ad_delivery_regions, dtype: object"
            }
        ]
    }
}

In [ ]:
# estimated_audience_size_min > 500
filename = "uk-meta-ads-question-25-run-4-estimated_audience_size_min-2025-11-18T17-23-04-567713.json" # SET VALUE
with open(f"{FILEPATH}/{filename}") as fin:
    data = json.load(fin)

if "data" in data:
    df = pd.json_normalize(data["data"])
    df["estimated_audience_size.lower_bound"] = df["estimated_audience_size.lower_bound"].astype("int64") # NEEDS TO DECLARE INT64, AS SOME OF THEM CAME AS INT32
   
    schema = pa.DataFrameSchema(
        {
            "estimated_audience_size.lower_bound": pa.Column(
                pa.Int, 
                checks=pa.Check.greater_than_or_equal_to(500),
                nullable=False,  
                title="Estimated audience size - Lower"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have audience size greater than the set estimated_audience_size_min parameter.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Found ads that have audience size lower than the set estimated_audience_size_min parameter")
        print(err)

✅ Validation Successful: All ads have audience size greater than the set estimated_audience_size_min parameter.

In [109]:
# language: en
filename = "uk-meta-ads-question-25-run-5-languages-2025-11-18T17-23-07-162126.json"
with open(f"{FILEPATH}/{filename}") as fin:
    data = json.load(fin)

if "data" in data:
    df = pd.DataFrame(data["data"])
    df["languages"] = df["languages"].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else x)


    schema = pa.DataFrameSchema(
        {
            "languages": pa.Column(
                checks=pa.Check.equal_to("en"),
                nullable=False,  
                title="Languages"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have information regarding language and it's the correct language set in language parameter.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Found ads that don't have or are not from the language set in the language parameter")
        print(err)

✅ Validation Successful: All ads have information regarding language and it's the correct language set in language parameter.

### RELEVANCE

**OC26: Does the platform allow the use of temporal filters to retrieve data on ads?**

*This item verifies whether the ad repository allows filtering ad campaign data based on the time period during which the ads were served. The assessment should test queries with temporal filters to confirm that results accurately reflect the specified date ranges.*

In [111]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True,
            "ad_delivery_date_max": "2025-10-15", # FEEL FREE TO CHANGE DATES
            "ad_delivery_date_min": "2025-10-01" # FEEL FREE TO CHANGE DATES
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No ads were found")
    print(response)

Got 25 ads in a single request

,id,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time
0,1319582746241612,2025-10-01,2025-10-02,2025-10-03
1,1769832226983707,2025-10-08,2025-10-09,2025-10-09
2,2757687637759616,2025-10-08,2025-10-09,2025-10-11
3,3287991251366095,2025-10-08,2025-10-09,2025-10-11
4,707395975221816,2025-10-15,2025-10-15,2025-10-22
5,1823552321597902,2025-10-15,2025-10-15,2025-10-22
6,2221930414885062,2025-10-07,2025-10-07,2025-10-09
7,565344519972786,2025-09-29,2025-10-02,2025-10-03
8,676225511673297,2025-09-29,2025-10-03,2025-10-05
9,777855338400759,2025-09-29,2025-10-04,2025-10-05
10,787838610647167,2025-09-29,2025-10-04,2025-10-04
11,810542094824538,2025-09-29,2025-10-04,2025-10-04
12,843422921443233,2025-09-29,2025-10-03,2025-10-05
13,846174007738030,2025-09-29,2025-10-03,2025-10-05
14,975467544762896,2025-09-29,2025-10-04,2025-10-05
15,1092087089581847,2025-09-29,2025-10-04,2025-10-04
16,1128106169424719,2025-09-29,2025-10-04,2025-10-05
17,1129385371998276,2025-09-29,2025-10-04,2025-10-05
18,1175959227912420,2025-09-29,2025-10-02,2025-10-03
19,1244905970724989,2025-09-29,2025-10-02,2025-10-03
20,1266488598823984,2025-09-29,2025-10-04,2025-10-04
21,1270529698207213,2025-09-29,2025-10-02,2025-10-03
22,1307746434378023,2025-09-29,2025-10-02,2025-10-03
23,1320306119817868,2025-09-29,2025-10-03,2025-10-04
24,1331099441907035,2025-09-29,2025-10-04,2025-10-04

In [112]:
df = pd.DataFrame(response["data"])
df["ad_delivery_start_time"] = pd.to_datetime(df["ad_delivery_start_time"])
start_date = datetime(year=2025, month=10, day=1)
end_date = datetime(year=2025, month=10, day=15)

schema = pa.DataFrameSchema({
    "ad_delivery_start_time": pa.Column(
        pa.DateTime,
        pa.Check(lambda s: s.between(start_date, end_date, inclusive="both"), 
                 name="DateRangeCheck"),
        nullable=False
    )
})
try:
    schema.validate(df, lazy=True)
    print("✅ Validation Successful: All ads are between date range.")

except SchemaErrors as err:
    print("❌ Validation Failed: Found ads outside date range.")
    print(err)

✅ Validation Successful: All ads are between date range.

**OC27: Does the platform allow filtering advertising data by ad category?**

*This item verifies whether the ad repository allows filtering ad campaign data based on any possible categories assigned at the time of ad creation. The assessment should run test queries with category filters to confirm that results align with the selected classifications.*

In [113]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,age_country_gender_reach_breakdown,br_total_reach,bylines,currency,delivery_by_region,demographic_distribution,estimated_audience_size,impressions,languages,page_id,page_name,publisher_platforms,spend,target_ages,target_gender,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "EMPLOYMENT_ADS", # FEEL FREE TO CHANGE CATEGORY
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in EMPLOYMENT_ADS in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found in EMPLOYMENT_ADS")
    print(response)

Got 25 in EMPLOYMENT_ADS in a single request

,id,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_titles,ad_delivery_start_time,age_country_gender_reach_breakdown,languages,page_id,page_name,publisher_platforms,target_ages,target_gender,target_locations,total_reach_by_location,ad_creative_link_descriptions,ad_delivery_stop_time
0,1548921109481590,2025-11-18,[Learn more about Priory. Mental Health Career...,"[jobs.priorygroup.com, jobs.priorygroup.com, j...","[Find your new role with Priory, Find your new...",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],5944538380,Indeed,"[facebook, instagram, audience_network, threads]","[18, 65]",All,"[{'name': 'Bristol, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 1}]",NaN,NaN
1,1373133414457420,2025-11-18,[👋 Step into a role at Co-op to work in an org...,"[coop.co.uk, coop.co.uk, coop.co.uk]","[Become a Team Leader, Become a Team Leader, B...",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],10150110761225377,Co-op,"[facebook, instagram]","[18, 65]",All,"[{'name': 'Sandhurst, United Kingdom', 'num_ob...","[{'key': 'GB', 'value': 2}]","[Find a role near you, Find a role near you, F...",NaN
2,831141929646269,2025-11-18,[👋 Step into a role at Co-op to work in an org...,"[coop.co.uk, coop.co.uk, coop.co.uk]","[Become a Team Leader, Become a Team Leader, B...",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],10150110761225377,Co-op,"[facebook, instagram]","[18, 65]",All,"[{'name': 'Sandhurst, United Kingdom', 'num_ob...","[{'key': 'GB', 'value': 77}]","[Find a role near you, Find a role near you, F...",NaN
3,1155068040102937,2025-11-18,[👋 Step into a role at Co-op to work in an org...,"[coop.co.uk, coop.co.uk, coop.co.uk]","[Apply now, Apply now, Apply now]",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],10150110761225377,Co-op,"[facebook, instagram]","[18, 65]",All,"[{'name': 'Central Worthing, Worthing, United ...","[{'key': 'GB', 'value': 11}]","[Find a role near you, Find a role near you, F...",NaN
4,1111750867697594,2025-11-18,[👋 Step into a role at Co-op to work in an org...,"[coop.co.uk, coop.co.uk, coop.co.uk]","[Apply now, Apply now, Apply now]",2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],10150110761225377,Co-op,"[facebook, instagram]","[18, 65]",All,"[{'name': 'Central Worthing, Worthing, United ...","[{'key': 'GB', 'value': 31}]","[Find a role near you, Find a role near you, F...",NaN
5,1555182309136039,2025-11-18,[Ever wondered what makes GSK such a great pla...,[d.hodes.com],[GSK: Your Career in Global Health​],2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],512439245793683,GSK careers,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Barnard Castle, United Kingdom', 'n...","[{'key': 'GB', 'value': 180}]",NaN,NaN
6,1178485803687227,2025-11-18,[Want to be part of something bigger? 🌍 ​\n\nK...,[gsk.com],[GSK: Your Career in Global Health​],2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],123311187737843,GSK,[instagram],"[18, 65]",All,"[{'name': 'Barnard Castle, United Kingdom', 'n...","[{'key': 'GB', 'value': 15}]",NaN,NaN
7,708536035174709,2025-11-18,[“I changed careers and never looked back.” – ...,[fb.com],[“I changed careers and never looked back.” – ...,2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],308731479193928,Carr Gomm,[facebook],"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 304}]",NaN,2025-11-18
8,1527697131989597,2025-11-18,[❗️Brand New Vacancy : Therapeutic Lead❗️\n\nW...,NaN,NaN,2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],1497175786981822,FEVACA,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 94}]",NaN,NaN
9,1900063050947561,2025-11-18,"[Every day, our people Go Beyond — sparking cr...",[careers.dsm-firmenich.com],"[Ready to go beyond?, Ready to go beyond?, Rea...",2025-11-18,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],188811517806232,dsm-firmenich,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Tulln, Austria', 'num_obfuscated': ...","[{'key': 'EU', 'value': 257}, {'key': 'GB', 'v...","[Find your next step, Find your next step, Fin...",NaN
10,1898880954359854,2025-11-18,[💡 Get insights on Work In the Netherlands as ...,[gethappyday.com],[Learn More About Working In the Netherlands a...,2025-11-18,"[{'country': 'MT', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 30}, {'key': 'GB', 'va...",[Learn more],NaN
11,1383632343174509,2025-11-18,[💡 Get insights on Work In the Netherlands as ...,[gethappyday.com],[Learn More About Working In the Netherlands a...,2025-11-18,"[{'country': 'NL', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 8}, {'key': 'GB', 'val...",[Learn more],NaN
12,1545293239952938,2025-11-18,[💡 Get insights on Work In the Netherlands as ...,[gethappyday.com],[Learn More About Working In the Netherlands a...,2025-11-18,"[{'country': 'LU', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 37}, {'key': 'GB', 'va...",[Learn more],NaN
13,2082065735658224,2025-11-18,[💡 Get insights on Work In the Netherlands as ...,[gethappyday.com],[Learn More About Working In the Netherlands a...,2025-11-18,"[{'country': 'RO', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 5}, {'key': 'GB', 'val...",[Learn more],NaN
14,1542606526984513,2025-11-18,[💡 Get insights on Work In Europe As A Home Ca...,[gethappyday.com],[🇪🇺 Learn More About Work In Europe As A Home ...,2025-11-18,"[{'country': 'CZ', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 29}, {'key': 'GB', 'va...",[Learn more],NaN
15,2071606827003395,2025-11-18,[💡 Get insights on Work In Europe As A Home Ca...,[gethappyday.com],[🇪🇺 Learn More About Work In Europe As A Home ...,2025-11-18,"[{'country': 'CY', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 3}, {'key': 'GB', 'val...",[Learn more],NaN
16,4254216634822354,2025-11-18,[💡 Get insights on Work In Europe As A Nursing...,[gethappyday.com],[🇪🇺 Learn More About Work In Europe As A Nursi...,2025-11-18,"[{'country': 'RO', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 46}, {'key': 'GB', 'va...",[Learn more],NaN
17,4177795412536947,2025-11-18,[💡 Get insights on Work In Europe As An Elderl...,[searchrelayr.com],[🇪🇺 Learn More About Work In Europe As An Elde...,2025-11-18,"[{'country': 'AT', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 22}, {'key': 'GB', 'va...",[Learn more],NaN
18,876203268908265,2025-11-18,[💡 Get insights on Work In Europe As An Elderl...,[gethappyday.com],[🇪🇺 Learn More About Work In Europe As An Elde...,2025-11-18,"[{'country': 'SE', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 3}, {'key': 'GB', 'val...",[Learn more],NaN
19,1627297061969484,2025-11-18,[💡 Get insights on Work In Europe As A Nurse. ...,[gethappyday.com],[🇪🇺 Learn More About Work In Europe As A Nurse...,2025-11-18,"[{'country': 'PL', 'age_gender_breakdowns': [{...",[en],854290684431002,Healing Roots Health,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 85}, {'key': 'GB', 'va...",[Learn more],NaN
20,871100715574453,2025-11-17,"[SAMH is recruiting in Castlemilk, Glasgow 📍\n...",[samh.org.uk/information/work-with-us],[Ready for a fresh start?],2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],304265286356048,SAMH,"[facebook, instagram, audience_network]","[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 7723}]",[SAMH is Scottish Action for Mental Health.],NaN
21,24221556070854229,2025-11-17,[Learn broadly about Car repair],[www.exploreverity.com],[Learn broadly about Car repair],2025-11-18,"[{'country': 'RE', 'age_gender_breakdowns': [{...",[en],155867200945468,PureWay Health,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 2}, {'key': 'GB', 'val...",[Discover more information about Car repair],NaN
22,1168640371480639,2025-11-17,[🚨 Come join our Bristol team as a -7.5T Deliv...,[fb.me],[Get Paid to Drive in Bristol],2025-11-18,"[{'country': 'GB', 'age_gender_breakdowns': [{...",[en],163741470990236,Outbox Recruitment,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Severn Beach, United Kingdom', 'num...","[{'key': 'GB', 'value': 80}]",[Join a fast-growing home delivery team],NaN
23,1176845997884020,2025-11-17,[Learn in the guide about different work progr...,[www.rvguide.com],[Learn more in the guide],2025-11-18,"[{'country': 'DE', 'age_gender_breakdowns': [{...",[en],768494849687598,Looping - Jobs,"[facebook, instagram, messenger]","[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 20}, {'key': 'GB', 'va...",NaN,NaN
24,1380398986823325,2025-11-17,[✨ Get a FREE Colgate sample kit!\nTry new too...,[mywallet.mywordshindi.com],[FREE Colgate Samples 🪥🦷],2025-11-18,"[{'country': 'BE', 'age_gender_breakdowns': [{...",[en],794418017089951,Entertainment Daily,"[facebook, instagram, audience_network, messen...","[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 7}, {'key': 'GB', 'val...",[Try Colgate’s newest formulas for FREE. Limit...,NaN

**OC28: Does the platform allow filtering advertising data by geographic location?**

*This item assesses whether the ad repository allows filtering data by one or more subnational geographic locations where the ads were served. The assessment should test queries with location filters to confirm that results match the specified areas.*

In [8]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,delivery_by_region"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "delivery_by_region": ["Wales"], # FEEL FREE TO CHANGE REGION
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

No data found
{'error': {'message': 'An unknown error has occurred.', 'type': 'OAuthException', 'code': 1, 'fbtrace_id': 'AuviBPiPclMfb5Q7v_pINV-'}}

In [9]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,delivery_by_region"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "delivery_by_region": ["Wales"], # FEEL FREE TO CHANGE REGION
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

Got 25 in a single request

                   id                                 delivery_by_region
0    2000140754078974                                                NaN
1     873024729013840  [{'percentage': '0.835799', 'region': 'England...
2    1389542052586614  [{'percentage': '0.835052', 'region': 'England...
3    1231020129047078                                                NaN
4    1089813986421302  [{'percentage': '0.824675', 'region': 'England...
5    1180576226824789  [{'percentage': '0.866972', 'region': 'England...
6    2025553841632824  [{'percentage': '0.76129', 'region': 'England'...
7     843582031655873  [{'percentage': '0.768557', 'region': 'England...
8     846774491643583  [{'percentage': '0.001043', 'region': 'Abia St...
9    2346315129155988  [{'percentage': '0.026403', 'region': 'Abkhazi...
10   2012564479285185  [{'percentage': '0.824969', 'region': 'England...
11   1274493874401362  [{'percentage': '0.76311', 'region': 'England'...
12   1371926394432148  [{'percentage': '0.754839', 'region': 'England...
13   1863121540954685           [{'percentage': '1', 'region': 'Wales'}]
14   1368485208078803           [{'percentage': '1', 'region': 'Wales'}]
15   1981506379370038  [{'percentage': '0.829268', 'region': 'England...
16   1555995435442522  [{'percentage': '0.823054', 'region': 'England...
17   1199203642106844                                                NaN
18   2300548497060964  [{'percentage': '0.77983', 'region': 'England'...
19  24790185470677956  [{'percentage': '0.83', 'region': 'England'}, ...
20   1777267652977330  [{'percentage': '0.770833', 'region': 'England...
21   1620762299300723  [{'percentage': '0.761468', 'region': 'England...
22    851988117778431  [{'percentage': '0.815385', 'region': 'England...
23   2204355123308493  [{'percentage': '0.802817', 'region': 'England...
24   1157826822675744  [{'percentage': '0.791255', 'region': 'England...

In [10]:
# delivery_by_region: Dublin
def extract_regions(x):
    if isinstance(x, list) and len(x) > 0:
        return [d['region'] for d in x]
    return x

def check_delivery_region(regions):
    return regions.apply(lambda region_list: "Wales" in region_list)

if "data" in response:
    df = pd.DataFrame(response["data"])
    df["ad_delivery_regions"] = df["delivery_by_region"].apply(extract_regions)

    schema = pa.DataFrameSchema(
        {
            "ad_delivery_regions": pa.Column(
                checks=pa.Check(check_delivery_region),
                nullable=False,  
                title="Ad delivery regions"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads came from the region set in the geographic location filter.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Found ads that don't have or are not from the region set in the geographic location filter.")
        print(err)

❌ Validation Failed: Found ads that don't have or are not from the region set in the geographic location filter.
{
    "SCHEMA": {
        "SERIES_CONTAINS_NULLS": [
            {
                "schema": null,
                "column": "ad_delivery_regions",
                "check": "not_nullable",
                "error": "non-nullable series 'ad_delivery_regions' contains null values:0     NaN3     NaN17    NaNName: ad_delivery_regions, dtype: object"
            }
        ]
    }
}

In [13]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,delivery_by_region"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "delivery_by_region": ["London"], # FEEL FREE TO CHANGE REGION
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

No data found
{'error': {'message': 'An unknown error has occurred.', 'type': 'OAuthException', 'code': 1, 'fbtrace_id': 'Akeq-U43zWL3Mf9iqUWDvHd'}}

### ACCURACY

**OC29: Does the platform provide age and gender data on the audiences of ads?**

*This item verifies whether the platform provides data on the age and gender of audiences reached. The assessment should review the ad records to confirm that these breakdowns are available and consistently reported*

In [127]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,age_country_gender_reach_breakdown,demographic_distribution,target_ages,target_gender"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

Got 25 in a single request

,id,age_country_gender_reach_breakdown,target_ages,target_gender
0,4192086697717648,"[{'country': 'FR', 'age_gender_breakdowns': [{...","[18, 65]",All
1,566436209821750,"[{'country': 'FR', 'age_gender_breakdowns': [{...","[18, 65]",All
2,543784622115975,"[{'country': 'FI', 'age_gender_breakdowns': [{...","[18, 65]",All
3,569384776193327,"[{'country': 'AT', 'age_gender_breakdowns': [{...","[18, 65]",All
4,1780320716164479,"[{'country': 'FI', 'age_gender_breakdowns': [{...","[18, 65]",All
5,708779748236211,"[{'country': 'PT', 'age_gender_breakdowns': [{...","[18, 65]",All
6,1225703642407613,"[{'country': 'PT', 'age_gender_breakdowns': [{...","[18, 65]",All
7,990332916558558,"[{'country': 'PT', 'age_gender_breakdowns': [{...","[18, 65]",All
8,1256665679256719,"[{'country': 'DE', 'age_gender_breakdowns': [{...","[21, 65]",All
9,2029047231250712,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[18, 65]",All
10,468492669268944,"[{'country': 'PT', 'age_gender_breakdowns': [{...","[18, 65]",All
11,540462482317039,"[{'country': 'SE', 'age_gender_breakdowns': [{...","[18, 65]",All
12,927457872686945,"[{'country': 'ES', 'age_gender_breakdowns': [{...","[18, 65]",All
13,1118856549901694,"[{'country': 'AT', 'age_gender_breakdowns': [{...","[18, 65]",All
14,1149767699841006,"[{'country': 'EE', 'age_gender_breakdowns': [{...","[18, 65]",All
15,1198154008406828,"[{'country': 'EE', 'age_gender_breakdowns': [{...","[18, 65]",All
16,1645469656179516,"[{'country': 'IT', 'age_gender_breakdowns': [{...","[18, 65]",All
17,1681368622408808,"[{'country': 'FR', 'age_gender_breakdowns': [{...","[18, 65]",All
18,1699924333908780,"[{'country': 'RO', 'age_gender_breakdowns': [{...","[18, 65]",All
19,1990654091358510,"[{'country': 'CY', 'age_gender_breakdowns': [{...","[18, 65]",All
20,659209690345526,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[18, 65]",All
21,1510983603181878,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[18, 65]",All
22,573867262268518,"[{'country': 'MQ', 'age_gender_breakdowns': [{...","[18, 65]",All
23,1238312724100050,"[{'country': 'AT', 'age_gender_breakdowns': [{...","[18, 65]",All
24,1266941774632571,"[{'country': 'NL', 'age_gender_breakdowns': [{...","[18, 65]",All

In [128]:
if "data" in response:
    df = pd.json_normalize(response["data"])
    schema = pa.DataFrameSchema(
        {
            "age_country_gender_reach_breakdown": pa.Column( 
                nullable=False,  
                title="Age Country Gender Reach Breakdown"
            ),
            "target_ages": pa.Column(
                nullable=False,  
                title="Target Ages"
            ),
            "target_gender": pa.Column(
                nullable=False,  
                title="Target Ages"
            ),
            "demographic_distribution": pa.Column(
                nullable=False,  
                title="Target Ages"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have information about age and gender about ad audience.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing ads information about age and gender.")
        print(err)

❌ Validation Failed: Missing ads information about age and gender.
{
    "SCHEMA": {
        "COLUMN_NOT_IN_DATAFRAME": [
            {
                "schema": null,
                "column": null,
                "check": "column_in_dataframe",
                "error": "column 'demographic_distribution' not in dataframe. Columns in dataframe: ['id', 'age_country_gender_reach_breakdown', 'target_ages', 'target_gender']"
            }
        ]
    }
}

In [129]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,age_country_gender_reach_breakdown,demographic_distribution,target_ages,target_gender"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

Got 25 in a single request

,id,age_country_gender_reach_breakdown,demographic_distribution,target_ages,target_gender
0,2676039509409546,"[{'country': 'ES', 'age_gender_breakdowns': [{...","[{'percentage': '0.051429', 'age': '25-34', 'g...","[25, 65]",All
1,863253100206091,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,"[18, 65]",All
2,1193966449497472,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,"[18, 65]",All
3,1544865313368139,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,"[18, 65]",All
4,820201220997208,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.037698', 'age': '18-24', 'g...","[18, 65]",All
5,2304576016640979,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.023753', 'age': '18-24', 'g...","[18, 65]",All
6,1471437670627318,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.022901', 'age': '18-24', 'g...","[18, 65]",All
7,2355445218205574,"[{'country': 'IE', 'age_gender_breakdowns': [{...","[{'percentage': '0.035667', 'age': '18-24', 'g...","[20, 65]",All
8,1583691626406370,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.310861', 'age': '18-24', 'g...","[18, 65]",All
9,1158136649632381,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,"[20, 55]",All
10,766996016361133,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,"[20, 55]",All
11,1506911813892989,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,"[20, 55]",All
12,4072423809674987,"[{'country': 'ES', 'age_gender_breakdowns': [{...","[{'percentage': '0.019126', 'age': '18-24', 'g...","[18, 65]",All
13,1201738788490856,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.004717', 'age': '18-24', 'g...","[18, 65]",Women
14,1018345883784718,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.042683', 'age': '25-34', 'g...","[25, 65]",All
15,25547504004847190,"[{'country': 'GB', 'age_gender_breakdowns': [{...",NaN,"[18, 65]",All
16,865891392528045,"[{'country': 'NL', 'age_gender_breakdowns': [{...","[{'percentage': '0.10169', 'age': '18-24', 'ge...","[18, 65]",All
17,869895502220383,"[{'country': 'CZ', 'age_gender_breakdowns': [{...",NaN,"[18, 65]",All
18,2702739236731672,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.002443', 'age': '18-24', 'g...","[18, 65]",All
19,4075866789347012,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.02122', 'age': '18-24', 'ge...","[18, 65]",All
20,1491394831915817,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.029045', 'age': '18-24', 'g...","[18, 65]",All
21,1368507788086212,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.005035', 'age': '18-24', 'g...","[18, 65]",All
22,853565240499142,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.008651', 'age': '18-24', 'g...","[18, 65]",All
23,766947929732943,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.001131', 'age': '18-24', 'g...","[18, 65]",All
24,846137747884428,"[{'country': 'GB', 'age_gender_breakdowns': [{...","[{'percentage': '0.00353', 'age': '18-24', 'ge...","[18, 65]",Women

In [130]:
if "data" in response:
    df = pd.json_normalize(response["data"])
    schema = pa.DataFrameSchema(
        {
            "age_country_gender_reach_breakdown": pa.Column( 
                nullable=False,  
                title="Age Country Gender Reach Breakdown"
            ),
            "target_ages": pa.Column(
                nullable=False,  
                title="Target Ages"
            ),
            "target_gender": pa.Column(
                nullable=False,  
                title="Target Ages"
            ),
            "demographic_distribution": pa.Column(
                nullable=False,  
                title="Target Ages"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have information about age and gender about ad audience.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing ads information about age and gender.")
        print(err)

❌ Validation Failed: Missing ads information about age and gender.
{
    "SCHEMA": {
        "SERIES_CONTAINS_NULLS": [
            {
                "schema": null,
                "column": "demographic_distribution",
                "check": "not_nullable",
                "error": "non-nullable series 'demographic_distribution' contains null values:1     NaN2     NaN3     NaN9     NaN10    NaN11    NaN15    NaN17    NaNName: demographic_distribution, dtype: object"
            }
        ]
    }
}

**OC30: Does the platform provide subnational geographic data on the audience reached by ads?**

*This item verifies whether the platform provides data on the subnational geographic location of audiences reached. The assessment should review the ad records to confirm that such location breakdowns are available and consistently reported.*

In [131]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,delivery_by_region,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

Got 25 in a single request

,id,target_locations,total_reach_by_location
0,4192086697717648,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 36}]"
1,566436209821750,"[{'name': 'France', 'num_obfuscated': 0, 'type...","[{'key': 'EU', 'value': 11}]"
2,543784622115975,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2}]"
3,569384776193327,"[{'name': 'Austria', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 181}]"
4,1780320716164479,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6}]"
5,708779748236211,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 9}]"
6,1225703642407613,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 75}]"
7,990332916558558,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty...","[{'key': 'EU', 'value': 1}]"
8,1256665679256719,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 8}, {'key': 'GB', 'val..."
9,2029047231250712,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 65}]"
10,468492669268944,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 192}]"
11,540462482317039,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 4}]"
12,927457872686945,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 10002}]"
13,1118856549901694,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 13}]"
14,1149767699841006,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 2229}]"
15,1198154008406828,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 5213}]"
16,1645469656179516,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 26032}]"
17,1681368622408808,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 8067}]"
18,1699924333908780,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 74}]"
19,1990654091358510,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 6337}]"
20,659209690345526,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 127}]"
21,1510983603181878,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 122}]"
22,573867262268518,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 18506}]"
23,1238312724100050,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 1935}]"
24,1266941774632571,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '...","[{'key': 'EU', 'value': 3002}]"

In [132]:
def check_region_granularity(target_locations): 
    subnational_granularity = False
    if isinstance(target_locations, list) and len(target_locations) > 0:
        for location in target_locations:
            locations = location.get("name").split(",") 
            # TO DO: Check if only England/Scotland/Wales/Northern Ireland are left
            if len(locations) > 1:
                subnational_granularity = True
                break
    return subnational_granularity

def validate_granularity_column(s):
    return s.apply(check_region_granularity)

if "data" in response:
    df = pd.json_normalize(response["data"])
    schema = pa.DataFrameSchema(
        {
            "delivery_by_region": pa.Column( 
                nullable=False,  
                title="Delivery by region"
            ),
            "target_locations": pa.Column(
                pa.Object,
                pa.Check(validate_granularity_column, error="Ad lacks required subnational granularity."),
                nullable=False,  
                title="Target location"
            ),
            "total_reach_by_location": pa.Column(
                nullable=False,  
                title="Total reach by location"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have subnational geographic information about ad audience.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing ads subnational geographic information.")
        print(err)

❌ Validation Failed: Missing ads subnational geographic information.
{
    "SCHEMA": {
        "COLUMN_NOT_IN_DATAFRAME": [
            {
                "schema": null,
                "column": null,
                "check": "column_in_dataframe",
                "error": "column 'delivery_by_region' not in dataframe. Columns in dataframe: ['id', 'target_locations', 'total_reach_by_location']"
            }
        ]
    },
    "DATA": {
        "DATAFRAME_CHECK": [
            {
                "schema": null,
                "column": "target_locations",
                "check": "Ad lacks required subnational granularity.",

In [143]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,delivery_by_region,target_locations,total_reach_by_location"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

Got 25 in a single request

,id,delivery_by_region,target_locations,total_reach_by_location
0,2676039509409546,"[{'percentage': '0.005714', 'region': 'Aargau'...","[{'name': 'Netherlands', 'num_obfuscated': 0, ...","[{'key': 'EU', 'value': 50}, {'key': 'GB', 'va..."
1,863253100206091,NaN,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 70}]"
2,1193966449497472,NaN,"[{'name': 'London, United Kingdom', 'num_obfus...","[{'key': 'GB', 'value': 59}]"
3,1544865313368139,NaN,"[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 55}]"
4,820201220997208,"[{'percentage': '0.879447', 'region': 'England...","[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 507}]"
5,2304576016640979,"[{'percentage': '1', 'region': 'Scotland'}]","[{'name': 'Galashiels, United Kingdom', 'num_o...","[{'key': 'GB', 'value': 525}]"
6,1471437670627318,"[{'percentage': '1', 'region': 'Scotland'}]","[{'name': 'Peebles, United Kingdom', 'num_obfu...","[{'key': 'GB', 'value': 131}]"
7,2355445218205574,"[{'percentage': '6.2E-5', 'region': ''Asir Reg...","[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...","[{'key': 'EU', 'value': 88}, {'key': 'GB', 'va..."
8,1583691626406370,"[{'percentage': '0.835996', 'region': 'England...","[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 1879}]"
9,1158136649632381,NaN,"[{'name': 'West Bromwich, United Kingdom', 'nu...","[{'key': 'GB', 'value': 41}]"
10,766996016361133,NaN,"[{'name': 'West Bromwich, United Kingdom', 'nu...","[{'key': 'GB', 'value': 25}]"
11,1506911813892989,NaN,"[{'name': 'West Bromwich, United Kingdom', 'nu...","[{'key': 'GB', 'value': 19}]"
12,4072423809674987,"[{'percentage': '0.046448', 'region': 'Abu Dha...","[{'name': 'Netherlands', 'num_obfuscated': 0, ...","[{'key': 'EU', 'value': 34}, {'key': 'GB', 'va..."
13,1201738788490856,"[{'percentage': '0.832506', 'region': 'England...","[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 20083}]"
14,1018345883784718,"[{'percentage': '1', 'region': 'England'}]","[{'name': 'Margate, Kent, United Kingdom', 'nu...","[{'key': 'GB', 'value': 164}]"
15,25547504004847190,NaN,"[{'name': 'AB10 1, United Kingdom', 'num_obfus...","[{'key': 'GB', 'value': 85}]"
16,865891392528045,"[{'percentage': '0.049909', 'region': 'Abkhazi...","[{'name': 'Italy', 'num_obfuscated': 0, 'type'...","[{'key': 'EU', 'value': 2690}, {'key': 'GB', '..."
17,869895502220383,NaN,"[{'name': 'Italy', 'num_obfuscated': 0, 'type'...","[{'key': 'EU', 'value': 8}, {'key': 'GB', 'val..."
18,2702739236731672,"[{'percentage': '1', 'region': 'England'}]","[{'name': 'Ramsgate, United Kingdom', 'num_obf...","[{'key': 'GB', 'value': 1599}]"
19,4075866789347012,"[{'percentage': '1', 'region': 'England'}]","[{'name': 'LE4 0, United Kingdom', 'num_obfusc...","[{'key': 'GB', 'value': 373}]"
20,1491394831915817,"[{'percentage': '1', 'region': 'Wales'}]","[{'name': 'Wales, United Kingdom', 'num_obfusc...","[{'key': 'GB', 'value': 41019}]"
21,1368507788086212,"[{'percentage': '1', 'region': 'Scotland'}]","[{'name': 'G43 1, United Kingdom', 'num_obfusc...","[{'key': 'GB', 'value': 1562}]"
22,853565240499142,"[{'percentage': '1', 'region': 'England'}]","[{'name': 'Ramsgate, United Kingdom', 'num_obf...","[{'key': 'GB', 'value': 575}]"
23,766947929732943,"[{'percentage': '1', 'region': 'England'}]","[{'name': 'London, United Kingdom', 'num_obfus...","[{'key': 'GB', 'value': 3515}]"
24,846137747884428,"[{'percentage': '0.829814', 'region': 'England...","[{'name': 'United Kingdom', 'num_obfuscated': ...","[{'key': 'GB', 'value': 30595}]"

In [144]:
def check_region_granularity(target_locations): 
    subnational_granularity = False
    if isinstance(target_locations, list) and len(target_locations) > 0:
        for location in target_locations:
            locations = location.get("name").split(",") 
            # TO DO: Check if only England/Scotland/Wales/Northern Ireland are left
            if len(locations) > 1:
                subnational_granularity = True
                break
    return subnational_granularity

def validate_granularity_column(s):
    return s.apply(check_region_granularity)

if "data" in response:
    df = pd.json_normalize(response["data"])
    schema = pa.DataFrameSchema(
        {
            "delivery_by_region": pa.Column( 
                nullable=False,  
                title="Delivery by region"
            ),
            "total_reach_by_location": pa.Column(
                nullable=False,  
                title="Total reach by location"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have subnational geographic information about ad audience.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Missing ads subnational geographic information.")
        print(err)

❌ Validation Failed: Missing ads subnational geographic information.
{
    "SCHEMA": {
        "SERIES_CONTAINS_NULLS": [
            {
                "schema": null,
                "column": "delivery_by_region",
                "check": "not_nullable",
                "error": "non-nullable series 'delivery_by_region' contains null values:1     NaN2     NaN3     NaN9     NaN10    NaN11    NaN15    NaN17    NaNName: delivery_by_region, dtype: object"
            }
        ]
    }
}

**OC31: Does the platform include data on audience targeting criteria defined by advertisers?**

*This item verifies whether the platform provides data on audience targeting criteria defined by the advertiser when publishing ads (e.g., demographic and geographic segments, as well as interests, attitudes, behaviors, and keywords). The assessment should review ad records to confirm that these targeting parameters are available and consistently reported.*

In [149]:
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,estimated_audience_size,target_ages,target_gender,target_locations"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

Got 25 in a single request

,id,target_ages,target_gender,target_locations
0,4192086697717648,"[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type..."
1,566436209821750,"[18, 65]",All,"[{'name': 'France', 'num_obfuscated': 0, 'type..."
2,543784622115975,"[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ..."
3,569384776193327,"[18, 65]",All,"[{'name': 'Austria', 'num_obfuscated': 0, 'typ..."
4,1780320716164479,"[18, 65]",All,"[{'name': 'Finland', 'num_obfuscated': 0, 'typ..."
5,708779748236211,"[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty..."
6,1225703642407613,"[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty..."
7,990332916558558,"[18, 65]",All,"[{'name': 'Portugal', 'num_obfuscated': 0, 'ty..."
8,1256665679256719,"[21, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '..."
9,2029047231250712,"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ..."
10,468492669268944,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
11,540462482317039,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
12,927457872686945,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
13,1118856549901694,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
14,1149767699841006,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
15,1198154008406828,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
16,1645469656179516,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
17,1681368622408808,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
18,1699924333908780,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
19,1990654091358510,"[18, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ..."
20,659209690345526,"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ..."
21,1510983603181878,"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ..."
22,573867262268518,"[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '..."
23,1238312724100050,"[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '..."
24,1266941774632571,"[18, 65]",All,"[{'name': 'Guadeloupe', 'num_obfuscated': 0, '..."

In [150]:
if "data" in response:
    df = pd.json_normalize(response["data"])
    schema = pa.DataFrameSchema(
        {
            "target_ages": pa.Column(
                nullable=False,
                title="Target Ages"
            ),
            "target_gender": pa.Column(
                nullable=False,
                title="Target Gender"
            ),
            "target_locations": pa.Column(
                nullable=False,
                title="Target Locations"
            ),
        },
        strict=False
    )

    try:
        schema.validate(df, lazy=True)
        print("✅ OC31: Validation successful – for this sample, all ads include age, gender, and geographic targeting fields defined by the advertiser.")
    except SchemaErrors as err:
        print("❌ OC31: Validation failed – some ads are missing age, gender, or geographic targeting information.")
        print(err)
else:
    print("No data found")
    print(response)

✅ OC31: Validation successful – for this sample, all ads include age, gender, and geographic targeting fields defined by the advertiser.

In [145]:
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,estimated_audience_size,target_ages,target_gender,target_locations"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": True
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data found")
    print(response)

Got 25 in a single request

,id,target_ages,target_gender,target_locations,estimated_audience_size
0,2676039509409546,"[25, 65]",All,"[{'name': 'Netherlands', 'num_obfuscated': 0, ...",NaN
1,863253100206091,"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...",{'lower_bound': '1000001'}
2,1193966449497472,"[18, 65]",All,"[{'name': 'London, United Kingdom', 'num_obfus...","{'lower_bound': '100001', 'upper_bound': '5000..."
3,1544865313368139,"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...",{'lower_bound': '1000001'}
4,820201220997208,"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...","{'lower_bound': '100001', 'upper_bound': '5000..."
5,2304576016640979,"[18, 65]",All,"[{'name': 'Galashiels, United Kingdom', 'num_o...","{'lower_bound': '10001', 'upper_bound': '50000'}"
6,1471437670627318,"[18, 65]",All,"[{'name': 'Peebles, United Kingdom', 'num_obfu...","{'lower_bound': '10001', 'upper_bound': '50000'}"
7,2355445218205574,"[20, 65]",All,"[{'name': 'Ireland', 'num_obfuscated': 0, 'typ...",{'lower_bound': '1000001'}
8,1583691626406370,"[18, 65]",All,"[{'name': 'United Kingdom', 'num_obfuscated': ...",{'lower_bound': '1000001'}
9,1158136649632381,"[20, 55]",All,"[{'name': 'West Bromwich, United Kingdom', 'nu...","{'lower_bound': '100001', 'upper_bound': '5000..."
10,766996016361133,"[20, 55]",All,"[{'name': 'West Bromwich, United Kingdom', 'nu...","{'lower_bound': '10001', 'upper_bound': '50000'}"
11,1506911813892989,"[20, 55]",All,"[{'name': 'West Bromwich, United Kingdom', 'nu...",{'lower_bound': '1000001'}
12,4072423809674987,"[18, 65]",All,"[{'name': 'Netherlands', 'num_obfuscated': 0, ...",{'lower_bound': '1000001'}
13,1201738788490856,"[18, 65]",Women,"[{'name': 'United Kingdom', 'num_obfuscated': ...","{'lower_bound': '500001', 'upper_bound': '1000..."
14,1018345883784718,"[25, 65]",All,"[{'name': 'Margate, Kent, United Kingdom', 'nu...","{'lower_bound': '50001', 'upper_bound': '100000'}"
15,25547504004847190,"[18, 65]",All,"[{'name': 'AB10 1, United Kingdom', 'num_obfus...","{'lower_bound': '50001', 'upper_bound': '100000'}"
16,865891392528045,"[18, 65]",All,"[{'name': 'Italy', 'num_obfuscated': 0, 'type'...",{'lower_bound': '1000001'}
17,869895502220383,"[18, 65]",All,"[{'name': 'Italy', 'num_obfuscated': 0, 'type'...",{'lower_bound': '1000001'}
18,2702739236731672,"[18, 65]",All,"[{'name': 'Ramsgate, United Kingdom', 'num_obf...","{'lower_bound': '100001', 'upper_bound': '5000..."
19,4075866789347012,"[18, 65]",All,"[{'name': 'LE4 0, United Kingdom', 'num_obfusc...","{'lower_bound': '50001', 'upper_bound': '100000'}"
20,1491394831915817,"[18, 65]",All,"[{'name': 'Wales, United Kingdom', 'num_obfusc...",{'lower_bound': '1000001'}
21,1368507788086212,"[18, 65]",All,"[{'name': 'G43 1, United Kingdom', 'num_obfusc...","{'lower_bound': '50001', 'upper_bound': '100000'}"
22,853565240499142,"[18, 65]",All,"[{'name': 'Ramsgate, United Kingdom', 'num_obf...","{'lower_bound': '100001', 'upper_bound': '5000..."
23,766947929732943,"[18, 65]",All,"[{'name': 'London, United Kingdom', 'num_obfus...","{'lower_bound': '500001', 'upper_bound': '1000..."
24,846137747884428,"[18, 65]",Women,"[{'name': 'United Kingdom', 'num_obfuscated': ...","{'lower_bound': '500001', 'upper_bound': '1000..."

In [147]:
if "data" in response:
    df = pd.json_normalize(response["data"])
    schema = pa.DataFrameSchema(
        {
            "target_ages": pa.Column(
                nullable=False,
                title="Target Ages"
            ),
            "target_gender": pa.Column(
                nullable=False,
                title="Target Gender"
            ),
            "target_locations": pa.Column(
                nullable=False,
                title="Target Locations"
            ),
        },
        strict=False
    )

    try:
        schema.validate(df, lazy=True)
        print("✅ OC31: Validation successful – for this sample, all ads include age, gender, and geographic targeting fields defined by the advertiser.")
    except SchemaErrors as err:
        print("❌ OC31: Validation failed – some ads are missing age, gender, or geographic targeting information.")
        print(err)
else:
    print("No data found")
    print(response)

✅ OC31: Validation successful – for this sample, all ads include age, gender, and geographic targeting fields defined by the advertiser.

**OC32: Does the platform provide granular volume ranges for ad impressions?**

*This item verifies whether the ad repository provides impression values for ads, using ranges that closely approximate the actual numbers. Intervals should be no larger than 10% of the upper bound of the value range they represent. For example, values up to 1,000 impressions should be displayed in intervals no larger than 100; between 1,000 and 10,000 in intervals no larger than 1,000; between 10,000 and 100,000 in intervals no larger than 10,000; between 100,000 and 1 million or above, in intervals no larger than 100,000. The assessment should measure whether the reported intervals remain within this threshold across the different value ranges using the platform’s documentation or available data interfaces.*

In [155]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,impressions"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": False
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data in response")
    print(response)

Got 25 ads in a single request

                  id
0   4192086697717648
1    566436209821750
2    543784622115975
3    569384776193327
4   1780320716164479
5    708779748236211
6   1225703642407613
7    990332916558558
8   1256665679256719
9   2029047231250712
10   468492669268944
11   540462482317039
12   927457872686945
13  1118856549901694
14  1149767699841006
15  1198154008406828
16  1645469656179516
17  1681368622408808
18  1699924333908780
19  1990654091358510
20   659209690345526
21  1510983603181878
22   573867262268518
23  1238312724100050
24  1266941774632571

In [157]:
if response["data"]:
    df = pd.json_normalize(response["data"])
    required_cols = ["impressions.upper_bound", "impressions.lower_bound"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required impressions columns: {missing}")
    df["impressions.upper_bound"]= df["impressions.upper_bound"].astype(int)
    df["percentage"] = round((df["impressions.upper_bound"].astype(int) - df["impressions.lower_bound"].astype(int) ) / df["impressions.upper_bound"].astype(int)  * 100, 1)
    schema = pa.DataFrameSchema(
        {
            "percentage": pa.Column( 
                pa.Float,
                pa.Check.less_than_or_equal_to(10),
                nullable=False, 
                title="Interval between impressions values percentage"
            ),
            "impressions.upper_bound": pa.Column(
                nullable=False,  
                title="Impressions - Upper"
            ),
            "impressions.lower_bound": pa.Column(
                nullable=False,  
                title="Impressions - Lower"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have impressions granularity in the expected range.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Impressions granularity between lower and upper bound are larger than 10% of the upper bound")
        print(err)

ValueError: Missing required impressions columns: ['impressions.upper_bound', 'impressions.lower_bound']

In [158]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,impressions"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": False
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data in response")
    print(response)

Got 25 ads in a single request

                   id                                       impressions
0    2676039509409546        {'lower_bound': '0', 'upper_bound': '999'}
1     863253100206091        {'lower_bound': '0', 'upper_bound': '999'}
2    1193966449497472        {'lower_bound': '0', 'upper_bound': '999'}
3    1544865313368139        {'lower_bound': '0', 'upper_bound': '999'}
4     820201220997208        {'lower_bound': '0', 'upper_bound': '999'}
5    2304576016640979        {'lower_bound': '0', 'upper_bound': '999'}
6    1471437670627318        {'lower_bound': '0', 'upper_bound': '999'}
7    2355445218205574  {'lower_bound': '50000', 'upper_bound': '59999'}
8    1583691626406370    {'lower_bound': '2000', 'upper_bound': '2999'}
9    1158136649632381        {'lower_bound': '0', 'upper_bound': '999'}
10    766996016361133        {'lower_bound': '0', 'upper_bound': '999'}
11   1506911813892989        {'lower_bound': '0', 'upper_bound': '999'}
12   4072423809674987        {'lower_bound': '0', 'upper_bound': '999'}
13   1201738788490856  {'lower_bound': '20000', 'upper_bound': '24999'}
14   1018345883784718        {'lower_bound': '0', 'upper_bound': '999'}
15  25547504004847190        {'lower_bound': '0', 'upper_bound': '999'}
16    865891392528045  {'lower_bound': '15000', 'upper_bound': '19999'}
17    869895502220383        {'lower_bound': '0', 'upper_bound': '999'}
18   2702739236731672    {'lower_bound': '2000', 'upper_bound': '2999'}
19   4075866789347012        {'lower_bound': '0', 'upper_bound': '999'}
20   1491394831915817  {'lower_bound': '50000', 'upper_bound': '59999'}
21   1368507788086212    {'lower_bound': '2000', 'upper_bound': '2999'}
22    853565240499142        {'lower_bound': '0', 'upper_bound': '999'}
23    766947929732943    {'lower_bound': '3000', 'upper_bound': '3999'}
24    846137747884428  {'lower_bound': '45000', 'upper_bound': '49999'}

In [159]:
if response["data"]:
    df = pd.json_normalize(response["data"])
    required_cols = ["impressions.upper_bound", "impressions.lower_bound"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required impressions columns: {missing}")
    df["impressions.upper_bound"]= df["impressions.upper_bound"].astype(int)
    df["percentage"] = round((df["impressions.upper_bound"].astype(int) - df["impressions.lower_bound"].astype(int) ) / df["impressions.upper_bound"].astype(int)  * 100, 1)
    schema = pa.DataFrameSchema(
        {
            "percentage": pa.Column( 
                pa.Float,
                pa.Check.less_than_or_equal_to(10),
                nullable=False, 
                title="Interval between impressions values percentage"
            ),
            "impressions.upper_bound": pa.Column(
                nullable=False,  
                title="Impressions - Upper"
            ),
            "impressions.lower_bound": pa.Column(
                nullable=False,  
                title="Impressions - Lower"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have impressions granularity in the expected range.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Impressions granularity between lower and upper bound are larger than 10% of the upper bound")
        print(err)

❌ Validation Failed: Impressions granularity between lower and upper bound are larger than 10% of the upper bound
{
    "DATA": {
        "DATAFRAME_CHECK": [
            {
                "schema": null,
                "column": "percentage",
                "check": "less_than_or_equal_to(10)",
                "error": "Column 'percentage' failed element-wise validator number 0: less_than_or_equal_to(10) failure cases: 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 16.7, 33.3, 100.0, 100.0, 100.0, 100.0, 20.0, 100.0, 100.0, 25.0, 100.0, 33.3, 100.0, 16.7, 33.3, 100.0, 25.0"
            }
        ]
    }
}

**OC33: Does the platform provide granular investment ranges for ad spending?**

*This item verifies whether the ad repository provides spending values for ads, using ranges that closely approximate the actual amounts. Intervals should be no larger than 10% of the upper bound of the value range they represent. For example, values up to $100 should be displayed in intervals no larger than $10; between $100 and $1,000 in intervals no larger than $100; and between $1,000 and $10,000 in intervals no larger than $1,000. The assessment should measure whether the reported intervals remain within this threshold across the different value ranges using the platform’s documentation or available data interfaces.*

In [160]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,spend"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "ALL",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": False
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data in response")
    print(response)

Got 25 ads in a single request

                  id
0   4192086697717648
1    566436209821750
2    543784622115975
3    569384776193327
4   1780320716164479
5    708779748236211
6   1225703642407613
7    990332916558558
8   1256665679256719
9   2029047231250712
10   468492669268944
11   540462482317039
12   927457872686945
13  1118856549901694
14  1149767699841006
15  1198154008406828
16  1645469656179516
17  1681368622408808
18  1699924333908780
19  1990654091358510
20   659209690345526
21  1510983603181878
22   573867262268518
23  1238312724100050
24  1266941774632571

In [162]:
if response["data"]:
    df = pd.json_normalize(response["data"])
    required_cols = ["spend.upper_bound", "spend.lower_bound"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required spend columns: {missing}")
    df["spend.upper_bound"]= df["spend.upper_bound"].astype(int)
    df["spend.lower_bound"]= df["spend.lower_bound"].astype(int)
    df["percentage"] = round((df["spend.upper_bound"] - df["spend.lower_bound"] ) / df["spend.upper_bound"]  * 100, 1)
    schema = pa.DataFrameSchema(
        {
            "percentage": pa.Column( 
                pa.Float,
                pa.Check.less_than_or_equal_to(10),
                nullable=False, 
                title="Interval between spend values percentage"
            ),
            "spend.upper_bound": pa.Column(
                nullable=False,  
                title="Spend - Upper"
            ),
            "spend.lower_bound": pa.Column(
                nullable=False,  
                title="Spend - Lower"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have spend granularity in the expected range.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Spend granularity between lower and upper bound are larger than 10% of the upper bound")
        print(err)

ValueError: Missing required spend columns: ['spend.upper_bound', 'spend.lower_bound']

In [14]:
# Use this cell to develop an example where a request for ads is made.
# Describe the endpoint and the search parameters used.
# Please leave the result as the output of this cell.
fields="id,spend"
api_url=f"https://graph.facebook.com/v23.0/ads_archive?fields={fields}"
query = "health" # SET VALUE
payload={
            "access_token": ACCESS_TOKEN,
            "ad_active_status": "ALL",
            "ad_reached_countries": ["GB"],
            "ad_type": "POLITICAL_AND_ISSUE_ADS",
            "media_type": "ALL",
            "search_terms": query,
            "unmask_removed_content": False
        }
response = request_to_api(session, payload, api_url)
if "data" in response:
    print(f"Got {len(response['data'])} ads in a single request")
    df = pd.DataFrame(response["data"])
    display(df)
else:
    print("No data in response")
    print(response)

Got 25 ads in a single request

                  id                                      spend
0    910738265449473  {'lower_bound': '0', 'upper_bound': '99'}
1   1538121610742057  {'lower_bound': '0', 'upper_bound': '99'}
2   1233346365282183  {'lower_bound': '0', 'upper_bound': '99'}
3   1938522950057502  {'lower_bound': '0', 'upper_bound': '99'}
4   4081978308686111  {'lower_bound': '0', 'upper_bound': '99'}
5   2000140754078974  {'lower_bound': '0', 'upper_bound': '99'}
6    873409422033200  {'lower_bound': '0', 'upper_bound': '99'}
7   1059079012937652  {'lower_bound': '0', 'upper_bound': '99'}
8   1926937461217290  {'lower_bound': '0', 'upper_bound': '99'}
9   1219033433450981  {'lower_bound': '0', 'upper_bound': '99'}
10   851745284072823  {'lower_bound': '0', 'upper_bound': '99'}
11  1049712493902580  {'lower_bound': '0', 'upper_bound': '99'}
12   873024729013840  {'lower_bound': '0', 'upper_bound': '99'}
13  1389542052586614  {'lower_bound': '0', 'upper_bound': '99'}
14  1231020129047078  {'lower_bound': '0', 'upper_bound': '99'}
15  1089813986421302  {'lower_bound': '0', 'upper_bound': '99'}
16  1180576226824789  {'lower_bound': '0', 'upper_bound': '99'}
17  1498095961413180  {'lower_bound': '0', 'upper_bound': '99'}
18  2025553841632824  {'lower_bound': '0', 'upper_bound': '99'}
19   843582031655873  {'lower_bound': '0', 'upper_bound': '99'}
20   846774491643583  {'lower_bound': '0', 'upper_bound': '99'}
21  2346315129155988  {'lower_bound': '0', 'upper_bound': '99'}
22  1158410755937336  {'lower_bound': '0', 'upper_bound': '99'}
23   736862919435048  {'lower_bound': '0', 'upper_bound': '99'}
24   738416182612416  {'lower_bound': '0', 'upper_bound': '99'}

In [15]:
if response["data"]:
    df = pd.json_normalize(response["data"])
    required_cols = ["spend.upper_bound", "spend.lower_bound"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required spend columns: {missing}")
    df["spend.upper_bound"]= df["spend.upper_bound"].astype(int)
    df["spend.lower_bound"]= df["spend.lower_bound"].astype(int)
    df["percentage"] = round((df["spend.upper_bound"] - df["spend.lower_bound"] ) / df["spend.upper_bound"]  * 100, 1)
    schema = pa.DataFrameSchema(
        {
            "percentage": pa.Column( 
                pa.Float,
                pa.Check.less_than_or_equal_to(10),
                nullable=False, 
                title="Interval between spend values percentage"
            ),
            "spend.upper_bound": pa.Column(
                nullable=False,  
                title="Spend - Upper"
            ),
            "spend.lower_bound": pa.Column(
                nullable=False,  
                title="Spend - Lower"
            )
        },
        strict=False
    )
    try:
        schema.validate(df, lazy=True)
        print("✅ Validation Successful: All ads have spend granularity in the expected range.")
    except SchemaErrors as err:
        print("❌ Validation Failed: Spend granularity between lower and upper bound are larger than 10% of the upper bound")
        print(err)

❌ Validation Failed: Spend granularity between lower and upper bound are larger than 10% of the upper bound
{
    "DATA": {
        "DATAFRAME_CHECK": [
            {
                "schema": null,
                "column": "percentage",
                "check": "less_than_or_equal_to(10)",
                "error": "Column 'percentage' failed element-wise validator number 0: less_than_or_equal_to(10) failure cases: 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0"
            }
        ]
    }
}

In [16]:
df

                  id  spend.lower_bound  spend.upper_bound  percentage
0    910738265449473                  0                 99       100.0
1   1538121610742057                  0                 99       100.0
2   1233346365282183                  0                 99       100.0
3   1938522950057502                  0                 99       100.0
4   4081978308686111                  0                 99       100.0
5   2000140754078974                  0                 99       100.0
6    873409422033200                  0                 99       100.0
7   1059079012937652                  0                 99       100.0
8   1926937461217290                  0                 99       100.0
9   1219033433450981                  0                 99       100.0
10   851745284072823                  0                 99       100.0
11  1049712493902580                  0                 99       100.0
12   873024729013840                  0                 99       100.0
13  1389542052586614                  0                 99       100.0
14  1231020129047078                  0                 99       100.0
15  1089813986421302                  0                 99       100.0
16  1180576226824789                  0                 99       100.0
17  1498095961413180                  0                 99       100.0
18  2025553841632824                  0                 99       100.0
19   843582031655873                  0                 99       100.0
20   846774491643583                  0                 99       100.0
21  2346315129155988                  0                 99       100.0
22  1158410755937336                  0                 99       100.0
23   736862919435048                  0                 99       100.0
24   738416182612416                  0                 99       100.0